### ISSUE TITLE
Ajouter une note sur la performance des free filters

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#104]
Il n'y a pas d'index sur ceux là.

Message: "Using those filters can be long"

**Comment by grololo06** [comment]
Je serais plutôt pour rajouter les index.

**Comment by grololo06** [comment]
Je ne pense pas qu'il soit pertinent d'avertir l'utilisateur de choses qui _peuvent_ arriver, surtout quand elles n'arrivent pas (si les autres critères sont suffisamment sélectifs, ou si le projet n'est pas gros, la requête ira normalement vite). Ceci dit, je laisse la discussion ouverte autour du sujet de la performance perçue dans la page de classif manuelle.

**Comment by jiho** [comment]
Une possibilité serait de rajouter une note dans le message de chargement de la page (la petite roue rouge avec marqué loading) quand on utilise un free filter: "Loading (you used a free filter which may increase loading time)"
Si ça va vite, on ne verra pas le message, si ça va lentement, le message est pertinent.

Mais je ne sais pas si ce message est vraiment émis lors des requêtes avec les filtres ou si c'est une fois que la requête est finie et qu'il faut charger son résultat.

À voir lors de la refonte de l'UI de la page.

**Comment by grololo06** [comment]
Linked with  #461 on performance aspect.

**Comment by grololo06** [comment]
People got used to the clock progress bar presently displayed for queries.
