### ISSUE TITLE
Enlever l'option "OBJECTS to PREDICT" dans classification auto V2 niveau projet

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#142]
Actuellement, `Project > Train and predict identifications V2` ne fonctionne que pour les objets non-validés. Cela rend impossible le calcul d'une matrice de confusion correcte. Il y avait une option pour cela dans la précédente implémentation.

Exemple: sur ce projet http://ecotaxa.obs-vlfr.fr/prj/787 j'ai toujours l'erreur

```
No object to classify, perhaps all object already classified or you should adjust the perimeter settings as it was probably set to 'Not Validated' 
```

Avec la nouvelle organisation des menus, si on veut prédire juste sur "not validated" il faut faire le filtre approprié et passer par `Filtered > Train...`. Passer par `Project > Train...` suppose qu'on travaille sur tout le projet, donc aussi les objets non validés.

NB: cela était mal spécifié dans les spécifications du nouveau machine learning, désolé.

**Comment by picheral** [comment]
Cette option est en bas dans ADVANCED !

**Comment by jiho** [comment]
En effet, mais en fait il faudrait que cette option n'existe plus.
Si on fait `Project > Train and predict identifications` on est au niveau du projet, et donc on fait tout.
Si on ne veut prédire que les non-validated, on applique un filtre et on fait `Filtered > Train and predict identifications`

**Comment by grololo06** [comment]
La classification auto marche bien avec les filtres, donc redondance d'option au niveau projet.

**Comment by laurent-n** [comment]
Dans mon souvenir nous avions abordé ce point et volontairement laissé l'option afin d'éviter que dans le travail quotidien il ne soit trop souvent reprédit pour rien les objets déjà validé. A l'époque il avait été dit que le besoin de reprédire les objets validés n'était que pour des usages avancé et rare et que donc on gardait le comportement par défaut de ne prédire que les objets non validés et un option pour réaliser cette action beaucoup moins fréquente

**Comment by jiho** [comment]
L'objectif ici est de:
- simplifier le code
- éviter la redondance fonctionnelle: actuellement s'il y a un filtre sur le statut "Non-validated" uniquement, prédire via `Project > ...` ou via `Filtered > ...` donne la même chose (= prédiction des non-validated).
- éviter les comportements surprenants: filtre "Validated" , prediction par `Filtered > ...` aboutit à "No object to predict".

Cela dit, la vraie façon de régler ce pb sera de supprimer le menu `Project`, de ne garder que le comportement de `Filtered` et de garder le statut des filtres (et la possibilité de les supprimer) en conservant le header sur les pages autres que celle de classif. Une UI, cohérente partout tout le temps. Mais ceci n'est pas apparent à partir des issues parce qu'elles ne sont pas complètes.

**Comment by grololo06** [comment]
Fixed in 2.5.13.
