### ISSUE TITLE
Check the hierarchy in data identifiers at import time

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#144]
project > sample > acquisition > process > object > image

Currently objects reference all the above. Samples, acq and process only reference project. So, from the acquisitions it is impossible to link to the sample. This:
- annoying for metadata checking
- source of bugs if acquisition names are not unique per project (as seen previously)
- not how things were specified originally.

It needs to be fixed.

Cf #140 too.

**Comment by picheral** [comment]
Prévoir les cas où un niveau au moins est absent !
Prévoir le cas d'un même no de processing utilisé sur plusieurs samples.
Impact : Import et Subset

**Comment by picheral** [comment]
Faire RETROFIT

**Comment by jiho** [comment]
> Prévoir le cas d'un même no de processing utilisé sur plusieurs samples.

Pas possible. Il faut absolument que le système soit purement hiérarchique. Sinon on va se planter.

**Comment by grololo06** [comment]
Prévoir comment migrer la DB existante après ce "fix".

**Comment by grololo06** [comment]
Décision prise de fusionner sample & acquisition #367 , donc la hiérarchie n'est plus exactement celle décrite.

**Comment by grololo06** [comment]
Pb p.e. prj 2840 qui a 81 samples mais 1 seule acq/process -> split à faire

**Comment by grololo06** [comment]
Superseded by #367 and #460

**Comment by picheral** [comment]
Si je comprends bien, la solution que tu proposes est de râler si l'utilisateur essaie d'importer un truc qui ressemble à

object_id	sample_id	acq_id	
1			samp_a		1
2			samp_a		2
3			samp_b		1

parce que l'acquisition 1 appartient à la fois à samp_a et samp_b, c'est bien ça?

email JOI 2020/11/30 : 
C'est une solution mais, cela dit, ce cas là serait légitime: si on numérote simplement les acquisitions, chaque sample a une acquisition "1".

Ma suggestion pour cela serait, à l'import:

1. quand un id manque (sample, acq, process), le rajouter avec le nom "dummy_id" partout

2. re-calculer des ids unique comme la concatenation des ids des champs supérieurs; dans l'exemple-ci dessus, l'id de la première acquisition devient samp_a.1 et celle de la troisième devient samp_b.1, donc ils sont uniques

3. importer avec ces ids uniques, concaténés, pour définir les ids d'internes d'EcoTaxa mais garder l'id tel que fourni (non concaténé) dans orig_id. C'est également ce qui sera fourni à l'export (i.e. l'utilisateur récupère à la sortie ce qu'il a rentré).

**Comment by picheral** [comment]
Looking at the "How to" in the Import data page : 

ACQUISITION: metadata relative to the image acquisition
    acq_id [t] : unique identifier. If your acquisition differ for each sample you must have different identifier.
    acq_instrument [t] : name of the instrument (UVP, ZOOSCAN, FLOWCAM, etc.)
    acq_*** [t] : other fields relative to the acquisition. Up to 30 of them.
Il n'est rien dit sur le fait que cette Id ne peut être utilisée pour différents samples et cela serait cohérent de pouvoir conserver le même type d'acquisition pour differents samples au lieu de faire ce que nous avons défini dans Zooprocess en incluant le sampleId dans le ProcessId et le SampleId. Je soutiens donc l'idée de faire en sorte de rendre ces champs uniques en interne mais de permettre à l'utilisateur d'utiliser le même process/acquisition pour tous ses samples et de le récupérer en sortie.

**Comment by grololo06** [comment]
C'est en contradiction avec le titre même de cette issue, mais ça m'arrange vu que ça signifie que l'implémentation actuelle est OK.
Il me semble que la lecture du mot "Acquisition" est différente selon les cas.
1. Si par "acquisition" on entend "opération d'acquisition", i.e. un acte physique, je ne pense pas qu'il soit courant de mélanger plusieurs samples lors d'une opération -> unique par sample.
2. Si par "acquisition" on entend "caratéristiques d'une opération d'acquisition", effectivement on peut factoriser, puisque plusieurs opérations partagent les mêmes caractéristiques.

Par exemple, dans le cas 1. on pourrait rajouter une date d'acquisition, puisque c'est une opération qui a eu lieu.
Dans le cas 2. ça n'aurait pas de sens.

Je pense que la même problèmatique est au niveau en-dessous (process). Opération physique ou caractéristiques?

**Comment by jiho** [comment]
Decisions:

### Étape 1

- demander l'unicité de `sample_id` et `acq_id` au sein du projet.
- vérifier que chaque `acq_id` n'est que dans un et un seul `sample_id`; refuser l'import sinon
- créer l'unicité de `process_id` artificiellement pour l'instant, en concaténant `acq_id` + `process_id` pour ne pas casser l'import pour les utilisateurs de zooprocess
- sur la page d'import, documenter ainsi:

object_id [t] : identifier of the object, must be unique in the project. It will be displayed in the object page
passer process au dessus de acquisition!
process_id [t] : identifier of the image processing, must be unique in the project and be nested within an acquisition (see below). If missing, a dummy process identifier will be created.
acq_id [t] : identifier of the image acquisition, must be unique in the project and be nested within a sample (see below).  If missing, a dummy acquisition identifier will be created.
sample_id [t] : identifier of the sample, must be unique in the project.  If missing, a dummy sample identifier will be created.

Si pertinent, ajouter au niveau process: "If the `process_id` is not unique or nested within one acquisition, it will be made unique and nested upon import." mais je serai pour ne pas le mettre. C'est un workaround qui ne me semble pas pertinent à documenter.

### Étape 2

#544

### Étape 3

#367

**Comment by grololo06** [comment]
Closed as all dependents are.
