### ISSUE TITLE
CLASSIFICATION : Using at most n objects to train a model seems not really random

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#147]
To train a model
- Step 1: `N` projects are chosen as a training set
- Step 2: Some classes are chosen and the option "Use at most `nmax=5000` objects per category to train the model." is used
- Step 3: "Use Deep Learning Features" is checked

This should compute DL features for all objects which do not have them in all projects.

Result: the prediction ends correctly but upon a new try, some objects in some projects are still missing features.

Potential explanation: I suspect that the `nmax` objects are not chosen completely randomly across all projects, some projects end up not being used at all and therefore, their DL features are not computed.

If this is the case, this causes at least two problems:
- DL features which were expected to be computed are actually not
- most importantly, the objects are chosen from only a few projects, which may not reflect the full variability in the training set. They should really be chosen randomly across all projects.

**Comment by grololo06** [comment]
From the code, there is no DL specific treatment in object selection. Also I suspect that having "random_value" _fixed_ in the DB does not improve things. However I would need a test case, i.e. project and classification parameters, seen behavior vs expected one,  to progress on this topic.

**Comment by picheral** [comment]
It would be great to get a Random computed everytime we need it instead of a definite random in the DB.

**Comment by grololo06** [comment]
I agree with @picheral but this is another issue. I need a proper test case to solve the present issue if it's still relevant.

**Comment by grololo06** [comment]
From today's code:
- Missing "SCN features" are computed for all involved project, regardless of the random selection
- The randomness is indeed per category, and this is properly told in the page, so yes, with no luck, a project might be ignored.
