### ISSUE TITLE
Move taxa autocompletion panel to center of window

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#173]
When something is typed in the taxon selection box, the text field appears large and center screen so that the users sees what gets autocompleted better. Like this:

![screen shot 2018-05-17 at 17 34 38](https://user-images.githubusercontent.com/18445/40188366-0f878ffa-59fa-11e8-975b-38e9ff2c5012.png)

We could think to make the initial text field smaller (and the buttons next to it larger) or even remove it completely.

**Comment by grololo06** [comment]
I don't think it's a good idea but let's ask users.

**Comment by jiho** [comment]
An alternative solution is to keep the panel in its place but grow it as well as the text inside. It is a central piece of user interaction and is currently inconspicuous.

**Comment by grololo06** [comment]
In current usability study/survey, the field is in bottom center of the page.
![image](https://user-images.githubusercontent.com/20199778/135235720-6f9b0df1-9b14-4116-940a-c7b620c5b107.png)

**Comment by grololo06** [comment]
JO is fine for closing, in favor of checking that lisibility is OK in the new layout.
