### ISSUE TITLE
Changer l'interface d'accès à EcoPart depuis EcoTaxa

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#178]
Avoir un switch au niveau du logo (drop down menu) et différents logos pour EcoTaxa et EcoPart.
Une fois dans EcoPart, le logo est celui d'EcoPart et le lien renvoie vers la page de garde d'EcoPart, pas celle d'EcoTaxa.

**Comment by picheral** [comment]
Pas d'accord... Chacun sa méthode !

**Comment by picheral** [comment]
JO Logo EcoPart STP.
Réutiliser général Intro du "I"
Changer LOGO et cible.

Sur Home, passer à 3 colonne plus boutons au dessus du texte

**Comment by picheral** [comment]
Changer dans l'onglet cf #152

**Comment by jiho** [comment]
Proposition de logo:

![screen shot 2018-07-06 at 09 38 48](https://user-images.githubusercontent.com/18445/42366074-8e44623c-8100-11e8-96ac-9b146a70e7dc.png)

**Comment by picheral** [comment]
VALIDE

**Comment by jiho** [comment]
La navigation entre les différents morceaux d'EcoTaxa est "confuse" à l'heure actuelle, comme le montrent les illustrations ci-dessous:

![scan-copieur-filet12112018154522_1-3](https://user-images.githubusercontent.com/18445/48354937-2fb87980-e693-11e8-9cae-450229b889fb.jpg)
![scan-copieur-filet12112018154522_2-3](https://user-images.githubusercontent.com/18445/48354938-2fb87980-e693-11e8-8b5b-714be25d6d1a.jpg)
![scan-copieur-filet12112018154522_3-3](https://user-images.githubusercontent.com/18445/48354939-2fb87980-e693-11e8-83aa-70cd39b26b48.jpg)

Voici une suggestion d'amélioration

Page d'accueil: laisser les 3 boutons, même s'il faudra trouver une meilleure solution à terme (installations d'EcoTaxa sans EcoPart).

Page dans le domaine EcoTaxa
![scan-copieur-filet12112018162826_1-2](https://user-images.githubusercontent.com/18445/48357278-79f02980-e698-11e8-938a-420db2a26076.jpg)

Page dans le domain EcoPart
![scan-copieur-filet12112018162826_2-2](https://user-images.githubusercontent.com/18445/48357372-b9b71100-e698-11e8-85dd-2815da5426d8.jpg)

\+ j'ai oublié, dans les deux cas, il faut une option "About" dans le menu de droite, juste avant "Administration", qui aboutit à un modal qui donne la version d'EcoTaxa à partir d'un fichier de version (et d'autres choses que nous pourrions du coup enlever de la page de garde). Ou alors il faut une indication de la version mais de façon automatique, en texte (pas comme des pixels dans une image), à côté du logo.

\+ #268

**Comment by picheral** [comment]
Le minimum a été fait. L'amélioration de l'UX reste souhaitable pou rune version future. Réfléchir au statut du module particule en particulier et dans le contexte de GOPPI. Reste donc en 2.x (later).

**Comment by picheral** [comment]
A revoir lors de la refonte d'EcoPart.

**Comment by grololo06** [comment]
Issue trop longue. Mettre dans une _autre_ issue le delta par rapport à la situation actuelle (sauf si Δ = 0 bien sûr).
