### ISSUE TITLE
Révision interface prédiction v2

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#185]
Revoir les spécifications initiales et les implémenter: https://docs.google.com/document/d/1WWdoJLrRyyq_5zHn-nr6d0FbeydGpnhW6sL8-PRj25o/

NB: JO doit finir de les revoir.

**Comment by grololo06** [comment]
@jiho le lien est mort, s'il y a une version + récente?

**Comment by jiho** [comment]
Non... Je ferme ça pour l'instant.
