### ISSUE TITLE
IMPORT DATABASE : tests compatibilité

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#219]
Avertir lorsque des problèmes d'importation de bases issues d'autres instances (mobile) pose problème en raison de différences de versions (et donc de structures de bases). Proposer : 

- d'importer en corrigeant

- de mettre à jour l'instance source avant extraction de la database

**Comment by picheral** [comment]
Version simple : détecter et arrêter le process pour indiquer qu'il faut mettre à jour l'instance source.

**Comment by grololo06** [comment]
La fonction n'existe plus.
