### ISSUE TITLE
Admin : page de gestion d'un utilisateur

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#225]
Page d'affichage des informations pour chaque projet:

- privilèges
- contributions
- date de dernière contribution

- Bouton global de suppression des privilèges
- Projets clicable permettant d'aller l’évacuer des différents projets via l'admin projet

cf #193

**Comment by jiho** [comment]
Il faut plus une page accessible au user et à l'application admin permettant d'éditer les droits d'un utilisateur: un tableau des projets (filtrable comme le reste si possible), avec une colonne "Privileges" contenant 4 radio buttons (none, view, annotate, manage) + une colonne avec le nom (id) de projet, ce qui rendra facile de faire participer un utilisateur à plein de projets (et de l'en enlever ensuite)

**Comment by grololo06** [comment]
La même page que celle permettant d'éditer un utilisateur ou une autre?

**Comment by picheral** [comment]
Il faut améliorer la page actuelle accessible à l'user manager et à l'appli manager conformément à ce que dit JO le 16//01/19.

**Comment by jiho** [comment]
Le use case est souvent de mettre une même personne sur _n_ projets d'un coup, ou de supprimer les permissions que qqun qui n'est plus actif sur _n_ projets. Cela, les administrateurs de nombreux projets ont autant besoin de le faire que le user, appli manager.

Une autre possibilité qui rendrait ça accessible à plus de monde serait d'utiliser l'objet dont nous disposons qui représente un groupe de projets: les collections. Un utilisateur peut créer une collection avec n projets *dont il est admin*. Ces collections auront probablement une page de settings. On pourrait donc imaginer que cette page contienne une section de permissions, similaire à celle des projets, dont les permissions sont héritées des projets (avec un donc des statuts intermédiaire: genre "Annotate (2), Manager (3)" qui signifie que l'utilisateur est annotator sur 2 projets de la collection et managers du 3 autres). Éditer les permissions au niveau de la collection irait les mettre à jour dans tous les projets de la collection (ce qui sera autorisé vu que le manager de la collection est manager de tous les projets).

Ce qui manque c'est une information de dernière activité des utilisateurs sur le projet/la collection. Pour les projets, cela ser fait pour la page About project #382. Il sera possible de l'afficher là aussi.

**Comment by grololo06** [comment]
Clarified in #638
