### ISSUE TITLE
Modeles prediction  : outil de purge

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#227]
Fournir un outils à l'appp manager pour qu'il puisse purger des modèles !

**Comment by jiho** [comment]
Il suffit d'aller effacer les fichiers sur le serveur non?

**Comment by picheral** [comment]
L'idée serait finalement que le créateur du modèle puisse faire son ménage. Ce n'est guère facile à mettre en oeuvre car info ne sont pas dans le modèle et pages à créer (quelques heures).
Reporter à issue 2.X

**Comment by grololo06** [comment]
Il n'y a plus de modèle stocké.
