### ISSUE TITLE
TOPPER (Explore et Contribute)

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#237]
Lorsqu'on a selectionné UN projet, afficher le descriptif par hoover ou bouton "i"

**Comment by grololo06** [comment]
En laissant le curseur au-dessus du nom du projet ("Test LS" dans l'image ci-dessous)?
![Capture d’écran de 2020-03-25 08-31-35](https://user-images.githubusercontent.com/20199778/77512341-22102800-6e73-11ea-87b0-820c1b932385.png)

**Comment by picheral** [comment]
Dans Explore ou la page qui lui succèdera, lorsqu'un projet est sélectionné ou comme indiqué par Laurent le 25/03
Dans SELECT PROJECT pour faciliter le choix d'un projet.
Dans un projet lorsqu'il est ouvert en CONTRIBUTE
=> définir ensemble l'ergonomie

**Comment by grololo06** [comment]
Explore ne permettra plus de sélectionner un projet et #182 satisfait la présente je pense.
