### ISSUE TITLE
Add visual cue for classification

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#275]
In the classification page, the original specification had a picture of an organism to help classification. This is particularly useful for the "temp" categories or to guide novice sorters.

We should:
- add a picture for each taxon (and probably make the cell a bit bigger)
- by default use the first picture classified in the category
- have a "Use as poster picture" option in a right click menu on a picture and as a button on the object page that changes the image of the taxon to this one.

**Comment by grololo06** [comment]
Linked with #173 and #275

**Comment by grololo06** [comment]
Oulala! Complètement pas prévu.

**Comment by picheral** [comment]
A discuter !... mais on va avoir l'appli taxo pour cela ?

**Comment by grololo06** [comment]
30/09/2021 : Was thought to have larger d&d target and image indications. Closed waiting for further explorations on the topic.
