### ISSUE TITLE
Allow to choose which rank image to display by default

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#298]
Allow to configure, per project, which rank is displayed by default.
This would mean adding a setting in
https://github.com/oceanomics/ecotaxa_dev/blob/V2_0/appli/project/editproject.py
and then change rang=1 at line 23 of https://github.com/oceanomics/ecotaxa_dev/blob/V2_0/appli/project/main.py

Ideally here, if the user selects rank 3 as the default, the app should fall back on rank 2 of rank 3 is missing, and, if rank 2 is missing also, rank 1. I don't know if SQL queries allow this.

**Comment by grololo06** [comment]
Could we formalize as "last image" and "first image" or would it be also possible to pick an image in the "middle" of the set?

**Comment by jiho** [comment]
We keep the convention that rank 0 is the image displayed and we'll sort the question of which image(s) the deel learning algo works on there #299
