### ISSUE TITLE
Taxo server droits erronés

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#321]
Actuellement, il faut être PROJECT CREATOR pour créer un taxon... Si on ne l'est pas, le message d'erreur indique qu'il faut s'adresser au Project MANAGER.... qui n'a pas les droits de donner le privilège "PROJECT CREATOR". Il y a donc une erreur !!!

Il faut donc soit modifier le message, soit les privilèges. Je suis favorable à ce que ce privilège soit accessible au Project MANAGER et que le message indique qu'il faut demander au Project Manager de donner les droits de management du projet.

Autre option, on donne ces droits à l'annotateur et ce message n'apparaitra jamais !

**JO, Amanda, Votre opinion ?????**

**Comment by jiho** [comment]
Je pense que project manager est le niveau minimum et je serais d'avis de
même potentiellement mettre les annotateurs, car ils en auraient besoin.

**Comment by jiho** [comment]
Il faut que tous les annotateurs puissent créer des taxa.

**Comment by laurent-n** [comment]
Je pense que l'idée derrière le message de demander au Project manager etait non pas de lui demander le privilège mais de lui demander de créer le taxon pour l'annotateur. (ce qui ne ressort peut être pas dans le message)
Le but était de limiter un peu la population des créateur de taxon pour limiter un peu les erreurs d'autant plus qu'il n'y a pas de validation des taxons créés. L'idée était de faire un première validation avec les ressources du projet concerné.
Donc soit on change le message pour que ça soit plus clair qu'il faut demander la création du taxon au PM et non pas le droit de le faire.
Soit on descend au niveau annotateur, c'est à dire à beaucoup de monde, ce que je trouve risqué.

**Comment by grololo06** [comment]
A discuter tous les 4?

**Comment by jiho** [comment]
Je reviens sur mon commentaire, laisser tous les annotateurs le faire est problématique, surtout quand ce sont des étudiants peu expérimentés.

Donc une implémentation pourrait être:
- l'utilisateur tape un nom inexistant "Foobari bobucus"
- si cet utilisateur est Project manager, l'actuel "No results found + lien Create a new category" apparait.
- si cet utilisateur est < à project manager, il apparait "No results found. Ask the [project manager(s)] to create the category" ou [project manager(s)] est un mailto: vers le main project manager and sera plus tard un lien vers la page About project qui les listera tous.

**Comment by picheral** [comment]
Je partage la solution de JO.

**Comment by grololo06** [comment]
Ce sera "Request category" car il fallait faire court dans cet espace réduit.

**Comment by jiho** [comment]
David Broussard is project manager on 1447 and cannot create a taxon. He gets the error:

![image](https://user-images.githubusercontent.com/18445/100020176-ae4a6480-2ddf-11eb-9da4-e5aea300e81b.png)

**Comment by grololo06** [comment]
Too messy so closed in favor of #562
