### ISSUE TITLE
Allow stratified subsets

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#360]
It would be useful to be able to stratify subsets by sample (or acquisition/subsameple) instead of just globally (i.e. take n% or n object of each sample).

This should be trivial to implement (`GROUP_BY` before the sample).

**Comment by grololo06** [comment]
So far it's per category (partition by classif_id)

**Comment by grololo06** [comment]
Hi, this kind of UI?
![Capture d’écran de 2020-09-09 11-34-31](https://user-images.githubusercontent.com/20199778/92581899-8d6a7c80-f290-11ea-9c59-543369c6df1c.png)

**Comment by jiho** [comment]
Yes

**Comment by grololo06** [comment]
+1 as much in use by research people e.g. FL

**Comment by grololo06** [comment]
+ Valeur par défaut 100% of values

**Comment by jiho** [comment]
10% (not 100%) of values 😉

**Comment by grololo06** [comment]
Fixed in 2.5.8.
