### ISSUE TITLE
Long taxa name shift the display of images instead of wrapping under the image

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#371]
Example with Podolampas

![](https://user-images.githubusercontent.com/18468240/52058657-36ef7500-2568-11e9-9bdf-7d2e290d97db.png)

The last image is shifted to the right.

For Podolampas, the pb comes from the taxo db actually https://github.com/oceanomics/ecotaxoserver/issues/5

Still, should be taken into account more generally.

**Comment by jiho** [comment]
The correct fix for this is to *not* rely on a table(guessing the width) to display the images but on divs that the browser itself flows.

**Comment by grololo06** [comment]
After debate with users, the display algorithm should allow as many images as possible while keeping all the text under them. So no text ellipsis, but hyphenation when possible, to stick to the image width.

**Comment by grololo06** [comment]
Fixed in 2.5.3.
