### ISSUE TITLE
Faster taxon creation workflow

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#372]
When a taxon does not exist and needs to be created, instead of linking to the taxonomy edition page, where the user has to reclick "Create taxon", open the taxon creation modal with the taxon name already filled.

**Comment by grololo06** [comment]
I'm in favor of closing this one, as:
- It does not occur very often
- It's preferable that the user does some research before creating

**Comment by grololo06** [comment]
Definitely not OK in the light of recent evolutions.
