### ISSUE TITLE
Rôle "Project creator"

### ISSUE THREAD

**Issue by Elineau** [ecotaxa/ecotaxa_dev#386]
A partir du moment où nous avons un compte sur Ecotaxa on devrait avoir le droit de créer un projet et donc d'avoir accès au bouton CREATE NEW PROJECT.

A nous de faire un tri à une certaine fréquence décidée où on supprimerait tous les projets comportant 0 images.

**Comment by jiho** [comment]
Je suis d'accord, le bouton Create new project de la page https://ecotaxa.obs-vlfr.fr/prj/ devrait être accessible à tous.

**Comment by picheral** [comment]
Fait partie de la réflexion globale sur la refonte des permissions (cf tes specs).... et je ne partage pas complètement. Il faudrait en tout cas mettre des triple warning pour éviter les samples uniques par projet !

**Comment by grololo06** [comment]
Je ne partage pas complètement non plus, pour des questions de consommation de ressources et de "ménage" à faire.

**Comment by Elineau** [comment]
Pour que les gens ne créent pas des projets qui n'ont pas de sens ou des projets vides il faudrait retirer le droit de création de projet à tout le monde puisque une fois qu'on obtient ce droit on l'a à tout jamais. 
De plus, quand je donne aux gens le droit de créer des projets je ne suis pas juge de savoir si ils vont en être capable ou non et je ne vais pas suivre leur travaux pour m'assurer qu'ils le fassent bien. 
Je répond à ce genre de demande d'accès à la création de projet tout le temps, si c'était automatique ce serait pareil puisque j'accepte de le faire sans discuter mais au moins je n'aurai pas la sensation de faire qqchose qui n'a pas de sens.

**Comment by grololo06** [comment]
Supersed by #81 see last comment with permission table https://docs.google.com/spreadsheets/d/1wEfO-geVU1faTSHHO5vQNC3KMoJ3f_evi6AjjnlUNJM/edit#gid=0

**Comment by picheral** [comment]
Table des permissions validée.
