### ISSUE TITLE
Allow to archive old projects

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#388]
Make it possible to detect projects on which nothing has been done for a certain time (e.g. 2 years).

Then allow to email project owners that the project will be archived. The db portion for the project is dumped, the project is kept in a separate list and can be reloaded in the db (but that will take time).

Those projects should also not be presented for training machine learning models.

**Comment by jiho** [comment]
The cost outweighs the gains. We will not do it.

**Comment by grololo06** [comment]
Linked with #74 somehow
