### ISSUE TITLE
Raccourcie clavier : chgt de pages

### ISSUE THREAD

**Issue by Elineau** [ecotaxa/ecotaxa_dev#399]
Serait il possible de créer un raccourci avec les flèches droite/gauche du clavier pour pouvoir se balader dans les pages de classification ?
c'est bien plus rapide que de devoir viser les flèches avec la souris à chaque fois.

**Comment by grololo06** [comment]
Salut Amanda, peux-tu joindre une copie d'écran? Je ne vois pas les flêches dont tu parles.

**Comment by picheral** [comment]
Pas visibles en mode "FIT", seulement lorsque le nb de vignette est fixé.
![image](https://user-images.githubusercontent.com/18468240/81722685-06dc9480-9482-11ea-8816-26753c16c2a4.png)

**Comment by Elineau** [comment]
Quand il y a beaucoup d'objets dans une catégorie, on se retrouve avec bcp de pages et pour passer de l'une à l'autre il faut à chaque fois 
1. descendre en bas de page 
2. aller cliquer avec sa souris sur les flèches (images ci dessous) 

Et dès qu'on passe à la page suivante, rebelote : on descend en bas de page, etc..etc.. 
Pouvoir utiliser les flèches du clavier serait plus efficace 





__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 



De: "grololo06" <notifications@github.com> 
À: "oceanomics" <ecotaxa_dev@noreply.github.com> 
Cc: "Elineau" <elineau@obs-vlfr.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 12 Mai 2020 18:51:42 
Objet: Re: [oceanomics/ecotaxa_dev] Raccourcie clavier : chgt de pages (#399) 






Salut Amanda, peux-tu joindre une copie d'écran? Je ne vois pas les flêches dont tu parles.

**Comment by jiho** [comment]
Les flèches sont aussi mentionnées par #430 et il faut faire attention aux conflits avec le navigateur.

Modifieur (ALT, META, ?) + flèche?

**Comment by grololo06** [comment]
Will be CTRL-SHIFT-right arrow for next page and CRTL-SHITF-left arrow for previous page

**Comment by grololo06** [comment]
Fixed in 2.5.3.
