### ISSUE TITLE
Remove the duplication of projects and samples between EcoTaxa and EcoPart

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#405]
Projects should match 1:1 between EcoPart and EcoTaxa, once #335 (meta projects) are in place, sorting can be made consistent across projects.

All sample, acquis, process information in in EcoTaxa. It could be formatted in an enforced way if it makes the rest easier (to avoid having to go through the mapping everytime to find `aa`, `exp` etc.).

The duplication is currently causing bugs and making maintenance complicated.

**Comment by grololo06** [comment]
Intuitively, without knowing all the background, it seems in opposition with #376 , or?

**Comment by jiho** [comment]
The single EcoPart instance should still store all the EcoPart specific data (particle histograms, CTD profiles).

The metadata could be:
1. in EcoTaxa and the EcoPart instance is linked with a single EcoTaxa instance and shares its db;
2. either in both EcoPart and multiple EcoTaxa instances and kept always perfectly in sync;
3. in EcoTaxa instances only and dynamically fetched/modified by EcoPart through the API.
Repeating this in #376

**Comment by jiho** [comment]
It is decided that the metadata will be in both places and pushed by EcoPart to EcoTaxa to be kept in sync. See https://github.com/ecotaxa/ecopart/issues/17
