### ISSUE TITLE
Remove "import database" function and its twin "export database"

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#411]
- Is duplicate with plain import
- Is best way to put uncontrolled data and inconsistencies into the system
- Needs admin rights and local access to server, which might no be true if we "go to the cloud"

**Comment by laurent-n** [comment]
L'objectif de cette fonction était d'être capable d'importer facilement les données d'une instance mobile au retour de la mission après classification en mer.
A l'usage je ne sais pas comment cela se fait dans la pratique, est ce que cette fonction est utilisée ou est ce que ils passent par des export ?

**Comment by jiho** [comment]
We agreed on the suppression. The last projects were imported from Roscoff. It can be deleted now and, instead, regular export and import should be used, because they do a lot of checks that this function does not.

**Comment by laurent-n** [comment]
L'export est une fonction utile pour 

- Initialiser des bases mobiles 

- Initialiser des bases pour le développement ou le debuggage sans
récupérer toute la base. 

Vu la faible complexité de cette fonction je serais favorable à son
maintient.

**Comment by grololo06** [comment]
Done in 2.5.2.
