### ISSUE TITLE
EMODnet export of specific projects

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#426]
We have to make available to https://www.emodnet-biology.eu/ , in the right format, the data in several projects.

So there is development work to be able to reformat the data into the right data and packaging.
There is as well data cleanup to do, eventually one-shot with scripts, eventually manually.

@jiho, is there the list, e.g. of needed project IDs ?

**Comment by jiho** [comment]
Here is the list:

## MOOSE GE

    497, # 2015 180µ
    492, # 2016 180µ
    896  # 2017 200µ triple

## DYFAMED

    290
    291
    296
    2975
    298
    299
    333
    334
    871

## Point B

WP2

     301
     292
    2710
     295
     304
     297
     293
     300
     302
     303
     337
     756
    3044
     294

Régent

      15
     130
    2836
     745
     773
     336
     672
     754
     769
     771
     772
     776
     777
     895
     898
    2810
    2814
    2815
    2823
    2824
    2825
    2826
    2827
    2828
    2829
    2830
    2831
    2833
    2834
    2835
    2715
     768

Juday-Bogorov

      16
     163
     164
    1867
     127
     335
     757
     165


## PNMIR Cruises

     434
     435
     436
     443
     468
     826
    1244
     442

## Tara

WP2

    377
    378

Bongo

    397
    395

Régent

    412

Multinet

    714

eHFCM 20µm

    2274

**Comment by jiho** [comment]
Note from meeting today:
"Pour la mise à jour sur l'IPT, notre développeur Sylvain Morin (morin@gbif.fr) a mis en place un workflow d'automatisation sur l'IPT, n'hésitez pas à le contacter pour en savoir plus"

**Comment by grololo06** [comment]
A bit of specs on metadata:
*Keywords: plankton, imaging, ecotaxa + instrument
*Instrument should be common to all exported samples, an error is issued if not.
*Functional groups: plankton

**Comment by jiho** [comment]
The values should be concentrations http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL01/ with unit http://vocab.nerc.ac.uk/collection/P06/current/UPMM/

**Comment by jiho** [comment]
Sampling instruments should be taken in vocab L22 https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/L22/

If instrument does not exist there, use a generic term like http://vocab.nerc.ac.uk/collection/L05/current/22/

**Comment by jiho** [comment]
Sampling instrument may not be homogeneous in a collection (see MOOSE GE for example where the net mesh changes); imaging instrument must be.

**Comment by jiho** [comment]
`Speed of measurement platform relative to ground surface` is irrelevant here however.

**Comment by jiho** [comment]
`individualCount` in occurrence.txt should probably be removed because it is potentially misleading (could be taken as an abundance in the real world, which it is not)

**Comment by jiho** [comment]
See #527

**Comment by grololo06** [comment]
During the export, we should map "morpho"-typed taxa to the nearest "phylo" up in the category tree.
e.g. eudoxie<Abylopsis tetragona -> 'Abylopsis tetragona'
or dead<Copepoda -> Copepoda

**Comment by jiho** [comment]
I would drop the morpho/phylo distinction and just move up all taxa that are not in WoRMS. It may be the case that we add some phylogenetic taxa below what WoRMS provides (some branches are poorly developed in WoRMS) and we'll want the info to move in a degraded form rather than not at all.

**Comment by jiho** [comment]
The data should be exported so that identifications are consistent throughout the whole dataset (i.e. allow to remap categories, to merge them in particular, if the sub-categories are not sorted identically over the whole dataset).

**Comment by grololo06** [comment]
The specific projects were exported.
