### ISSUE TITLE
Sélection de vignette via le clavier

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_dev#430]
Serait-il possible de se déplacer d'une vignette à l'autre par les flèches du clavier plutôt que de reprendre la souris à chaque fois ?

On clique sur une vignette, on y assigne une catégorie ; puis on aimerait assigner une autre catégorie à la vignette juste à côté ou en bas (ou pas loin), on pourrait se déplacer avec les flèches via le clavier.

**Comment by grololo06** [comment]
Salut,
Les flèches c'est un peu compliqué, c'est déjà utilisé par le navigateur, par exemple pour faire du défilement horizontal/vertical. Par contre, pour le standard (champ suivant/champ précédent), normalement la touche TAB, je vois que rien ne se passe sur les vignettes. A moins que le comportement n'ait été volontairement inhibé? @jiho  ? @picheral ?

**Comment by jiho** [comment]
Rien de volontaire dont je me souvienne. Je me dis que Tab est habituellement pour passer d'un champ à un autre, e.g. sortir du champ texte qui permet de taper le nom de la catégorie. Or ce champ est est actif par défaut et c'est très utile. C'est peut-être pour ça que c'est désactivé.

Par ailleurs, je ne sais pas quel est le comportement de tab dans un élément de type table (actuellement la page est un table): est-ce que ça passe à la ligne en bout de ligne?
Il me semble que, pour que cela soit effectivement utile, il faudrait une navigation à 4 directions avec des flèches. Si les flèches ne sont pas possibles, on pourrait la jouer geek et utiliser les touches hjkl à la `vi`.

**Comment by grololo06** [comment]
Normalement (pas essayé), le TAB passe à la ligne suivante, enfin au premier élément de la ligne suivante.
La flêche bas a aussi une action dans le champ texte catégorie. Idée, on pourrait ruser en chopant le pavé numérique (4,8,2,6). Main droite sur la navigation, main gauche pour taper les petits noms.
Enfin, pour les _vrais_ ordinateurs, ceux avec un pavé numérique...

**Comment by jiho** [comment]
C'est une solution interessante si on considère que aucun nom de taxon ne commence par un chiffre, ce qui est probablement OK.

Je ne sais pas trop comment ça peut fonctionner d'avoir le champ taxo actif par défaut (ce qui est super utile et nécessaire) et des touches simples actives également, sans qu'il y ait de conflit. Il faudra peut-être un modifieur (Alt par exemple) pour passer en mode mouvement.

**Comment by grololo06** [comment]
Je tente de permettre à @Kikouliou de participer à la discussion en lui assignant (aussi) cette issue...

**Comment by Kikouliou** [comment]
good

**Comment by Kikouliou** [comment]
Afin d'avoir la même disposition que les flèches du clavier, je suggère les chiffres 1235 plutôt que 2468
Aussi, le ctrl ou le alt semble une bonne idée pour passer en mode déplacement pour éviter le conflit avec l'écriture dans le champ catégorie

**Comment by grololo06** [comment]
Fixed in 2.5.3.
