### ISSUE TITLE
Build a REST API to run existing functions

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#435]
Toutes les fonctionnalités de l'UI actuelle doivent passer par l’API de façon à s’assurer qu’elle soit fonctionnelle.

L’API sera également utilisée par d’autres clients et il faut donc que les questions d’authentification, de droits etc. soient réglées dans le backend.

Fonctionnalités = ce qui est dispo dans l’interface actuelle
- se connecter (déconnecter?)
- lister les projets accessibles
- uploader des données
- importer des données dans un projet
- faire un merge de projets
- au sein d'un projet filtrer des données selon différents critères (sample, lon, lat, depth, etc.)
Sur le résultat de filtres (ou sans filtre)
- faire un subset
- lancer une classif auto (avec différentes options)
- changer un statut de classif
- exporter des données
- télécharger les données exportées

Ces verbes de l'API lancent des actions et renvoient typiquement un statut et/ou une URL pour le téléchargement du résultat (export).

**Comment by jiho** [comment]
URL du type `https://api.ecotaxa.obs-vlfr.fr/v1` (i.e. avec un numéro de version).

**Comment by jiho** [comment]
From Martin Schroder: 

## Get batch data in: `POST /staging`

Upload data into a staging area for further processing (e.g. import into the EcoTaxa database).

Response: [201 Created](https://restfulapi.net/http-status-201-created/) with Location.

## Process batch data: `POST /batch`

```json
{
	import: {
		# url can be in /staging (ideally) or somewhere else
		url: "https://ecotaxa.obs-vlfr.fr/staging/123xyz.zip",
		# url: "https://ftp.geomar.de/UVP5/123xyz.zip",
		project_id: 123,
		# All the settings in the current Import UI:
        # images only, update meta-data, 
    	...
	}
}
```

Response: [202 Accepted](https://restfulapi.net/http-status-202-accepted/) with instructions of how to access the the job progess and the result (e.g. `Location: /task/42`).

## Get batch data out: `GET /batch`

```json
{
	# Specify the query
    #	easy case: <field>:<value>
    #	operators: $<operator>:<arguments>
    #		$or: OR operator
    # 		$near: Location is inside a certain radius around the specified point (GeoJSON)
    #		$in: value is included in the specified list
	query: {
    	project_id: 123,
    	location: {
    		$near: {
    			$geometry: [-26.99267, 18.00667],
				$maxDistance: <distance in meters>,
			}
		},
		status: {
            $in: ["annotated", "predicted"]
        }
	}
	# Specify the columns to include in the result
	# Wildcards should be allowed here
	include_columns: []
	# Specify the images (image rank) to include in the result
	include_images: [0] # all, none (default)
	# Specify the format
	# 	zip: current export format (ZIP of TSV and images)
	# 	tsv/csv: only valid if no images are selected
	# 	json: Directly usable in a web frontend
	format: "zip"
}
```

Response: [202 Accepted](https://restfulapi.net/http-status-202-accepted/) with instructions of how to access the the job progess and the result (e.g. `Location: /task/42`).

## Tasks

Batch processing operations  are typically long-running and therefore performed asynchronically. To watch the progress (and later retrieve the result) of these operations, the a task identifyer is returned in the response.

### `GET /task/<task_id`

Read information about a task.

Currently, a task can stall when further information is needed. In the proposed API, then `status` is set to "request" and a`request` field is provided. This format can be equally rendered in a UI or processed automatically.

Alternatively (and more natural for batch processing), the task would fail in this case with a detailed description what parameters were missing.

```json
{
	task_id: <task_id>,
    # Task status
    status: "scheduled" | "running" | "done" | "error" | "request",
    # A result URL is supplied when the task generated a file:
    result_url: ...,
    # Request further information:
    request: {
    	title: "Do you want the blue pill or the red pill?",
    	fields: [
    		{
                type: "select",
                label: "Color",
                name: "color",
                values: [
                    "Red",
                    "Blue"
                ]
            }
    	]
	}
}
```

**Comment by jiho** [comment]
### Example using the proposed API

- MorphoCluster fetches images for processing

  ```json
  # GET /batch
  {
      # Get unvalidated data for the projects 123, 42, 1337, and 26.
  	"query": {
      	project_id: {"$in": [123, 42, 1337, 26]},
  		status: { "$neq": "validated"},
  	}
  	# We need no further metadata
  	include_columns: []
  	# Use images of rank 0
  	include_images: [0] # all, none (default)
  	# Images require zip output format
  	format: "zip"
  }
  ```

- MorphoCluster does its thing (cluster, approve, grow, annotate, ...)

- New taxa are created using the API:

  ```json
  # POST /taxonomy
  {
      name: "Jackalope"
      # If there is a unieuk_id, supply it here:
      unieuk_id: ...,
      parent_id: 8910 # "Fearsome Critters"
  }
  # Response: new <taxon_id>
  ```

- The upstream taxa IDs are assigned to MorphoCluster nodes.

- MorphoCluster creates an output zip and uploads it to EcoTaxa:

  ```json
  # Upload data
  # POST /staging
  # Response: https://ecotaxa.obs-vlfr.fr/staging/123xyz.zip
  
  # Create new project
  # POST /project
  # Response: new <project_id>
  
  # POST /batch
  {
  	import: {
  		url: "https://ecotaxa.obs-vlfr.fr/staging/123xyz.zip",
  		project_id: <project_id>,
  	}
  }
  ```

**Comment by grololo06** [comment]
It was obviously an error from project management point of view to leave this huge issue opened. What's left is now in individual issues.
