### ISSUE TITLE
Build an object query API

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#436]
In addition to the functional API #435 , it is necessary to be able to query the database and directly get results in the form a table of data.

One possibility is to revolve all queries around object ids.

Within a project, `SELECT` objects `WHERE` some properties are matched = at least those available in the interface = sample name, lat, lon, date, time, time of day, etc. Get the object ids as a result.

For a list of object ids:

1.  get some properties, at object, acq, process, sample level: classification, morphological feature (area), pixel size, latitude, software processing version, etc. = all the metadata at the various levels of EcoTaxa. When a property is requested and does not exist, return a NULL instead and emit a warning

    In that case, the call returns a tsv table similar to the one of the usual export (same column names etc.) but with only the requested data.

2. change some properties, at any level too. This allows to change the classification, change the classification status, etc.

    In that case, the call returns a success or error message, potentially for each object.

**Comment by jiho** [comment]
From Martin Schroeder: Query syntax
  - Look at MongoDB [[1]](https://docs.mongodb.com/manual/tutorial/query-documents/)[[2]](https://docs.mongodb.com/manual/reference/operator/query/).
  - JSON: Simple to parse and to transform to SQL queries and custom data transformations.

**Comment by grololo06** [comment]
Given the size of the DB, opening a general querying function like this gives the guarantee that some calls will last looooong minutes and people will complain (the API user, and the ones using the system via the Web as well). I propose to narrow to what's in the GUI, of which performance is/will be tuned.

**Comment by jiho** [comment]
Agreed that compound queries on multiple "free" fields should not be generally available.

The `SELECT * WHERE` functionality should indeed cover at least what is in the GUI (and what is in the `obj_head` database table):
- sample
- depth
- lat/lon
- date, time
- (instrument, but this will be at project level and if queries are per project, then it does not make sense here)
- taxon
- annotation person
- annotation status
- annotation time

If a couple extra free field can be added, then good. If this leads to people asking more or low performance, then this is out of the API. People quand just query everything based on the other filters and re-filter the results based on the whatever field they want on their side.

**Comment by grololo06** [comment]
Should be done during #607 as the data showed in the GUI is what is described here.

**Comment by grololo06** [comment]
Closed with #607
