### ISSUE TITLE
Visibilité sur notre rôle (viewer/annotator/manager dans chacun de nos projets

### ISSUE THREAD

**Issue by Elineau** [ecotaxa/ecotaxa_dev#441]
Il serait bien de voir en un coup d'oeil les rôles que nous avons sur chaque projet lorsque nous sommes sur la page "contribute to a project" ou "select project"
Pourquoi pas une icône V (pour viewer), A (pour annotator) et M (pour manager) ?

**Comment by grololo06** [comment]
@jiho , OK for you?

**Comment by jiho** [comment]
Oui!

**Comment by jiho** [comment]
It was actually already specified in a more general issue about the project selection: #182

**Comment by picheral** [comment]
OUI... mais peut-être à faire avec 182 car cela n'a pas de vraie urgence.

**Comment by grololo06** [comment]
Les grosses issues comme #182 font peur alors que celle-ci est sympathique :) Je me la prends.

**Comment by grololo06** [comment]
OK this issue is included fully in https://github.com/ecotaxa/ecotaxa_dev/issues/182#issue-325595028 so it can be closed
