### ISSUE TITLE
Création d'une  fonction de MAJ automatique des metadata UVP ECOTAXA à partir d'ECOPART

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#444]
De nombreuses metadata sont aujourd'hui et dans l'attente d'une refonte des application redondantes dans ECOTAXA et ECOPART. Nous considérons que celles d'ECOPART sont toujours meilleures.
Il faudrait donc une tache récurrente qui fasse la MAJ des metadata dans ECOTAXA à partir de celles d'ECOPART. Cette tache deviendra inutile mais est nécessaire aujourd'hui.

**Comment by grololo06** [comment]
Il faudrait la liste des metadata en question et un exemple de projets pour le test.

**Comment by picheral** [comment]
En attente de la refonte de la hiérarchie des bases dans Ecotaxa. Les données sont au niveau projet et sample dans Ecopart et à d'autres niveaux dans Ecotaxa.

**Comment by jiho** [comment]
Les métadonnées devront être poussées depuis EcoPart vers EcoTaxa, c'est le chemin le plus logique car les utilisateurs importeront côté EcoPart.
Cette issue est donc remplacée par https://github.com/ecotaxa/ecopart/issues/17
