### ISSUE TITLE
Compute ecologically meaningful measurements

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#455]
ESD, length and volume are relevant to compute from images. They can be computed from `area`, `major`, `minor` and `pixel size`. So

1. adopt a naming convention for `area`, `major`, `minor` (object level) and `pixel size` (sample/subsample level)
2. hardcode the computation of the derived features when those are present
3. present those derived features as the other object features (for sorting, display, prediction) and propose to add them for the export.

**Comment by grololo06** [comment]
`esd = 2*(sqrt(area/PI));` d'après #417 
Pour `length` et `volume`?

**Comment by jiho** [comment]
```
esd = 2*  sqrt(area/pi) * px_size
length = major * px_size
vol_spherical = 4/3 * pi * (esd/2)^3
vol_ellipsoid = 4/3 * pi * length * (minor * px_size)^2
```

**Comment by jiho** [comment]
Then biovolume in sea water, per sample/subsample can be computed as an addition/alternative to concentration (see #520)

```
organism unit biovolume in sea water [mm3/m3] = organism volume * subsampling rate / volume sampled [m3]
biovolume per sample/subsample [mm3/m3] = group_by(sample/subsample ID) then sum(unit biovolume)
```

**Comment by grololo06** [comment]
> Then biovolume in sea water, per sample/subsample can be computed as an addition/alternative to concentration (see #520)
> 
> ```
> organism unit biovolume in sea water [mm3/m3] = organism volume * subsampling rate / volume sampled [m3]
> biovolume per sample/subsample [mm3/m3] = group_by(sample/subsample ID) then sum(unit biovolume)
> ```

What is `organism volume`? I can see `vol_spherical `and `vol_ellipsoid`

**Comment by jiho** [comment]
Both are organism volume; the most common formula is `vol_spherical`

**Comment by jiho** [comment]
Superseeded by #619
