### ISSUE TITLE
Annotator/free filter: filtering for equality should be enabled for the text field

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa_dev#474]
Right now only "contains" is enabled, but that finds zoo_crust_cop and zoo_crust_cop_like when searching for "zoo_crust_cop".

**Comment by grololo06** [comment]
In free filter "Text field", you can use ^ for exact match at the beginning and $ for exact match at the end.
E.g. : if "oo" returns "pool", "goose", "zoo" and "oops" 
  then "^oo" only matches "oops", 
   and "oo$" only matches "zoo"
while  "^oo$" matches nothing.

**Comment by picheral** [comment]
Mettre l'info accessible !

**Comment by grololo06** [comment]
C'est le but du code commit + haut :)

**Comment by rkiko** [comment]
Seems I can not reopen this. I think what Marc means is that this information should be available on ecotaxa itself. I agree with this. So, a tooltip would be good that can be reached via a ? or i button, as in other cases.
