### ISSUE TITLE
Make currently active category hover or show in top bar

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa_dev#478]
When sorting, the previous category can be assigned using ctrl-d. However, the user might have forgotten this category and also might not be visible on the left side. It would be good to have this category constantly visible somewhere.

**Comment by picheral** [comment]
This category should be highlighted in yellow. If not, it is a bug !

**Comment by rkiko** [comment]
Yes, it is in yellow, but I have 100 categories, and if I scroll around in the categories or assign using the "type the name" option, then the category is not in view. So, I can not see the yellow ...

**Comment by grololo06** [comment]
Since 2.5.13, the last chosen category is visible in the select box.
