### ISSUE TITLE
Enable hot key assignment for often used categories

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa_dev#479]
Some categories are needed very often. E.g. in UVP projects copepoda, detritus, badfocus

It would be nice, if the user could assign some keys like:

Hitting 
1 = Copepoda
2 = detritus
3 = badfocus>

Another user might like to have:

1 = solitaryblack
2 = Aulacantha
3 = Aulosphaeridae

**Comment by jiho** [comment]
Missed this issue when I created another one : #618 
@rkiko if my description fits what you think, please close this one (I think the other is a bit more detailed).

**Comment by rkiko** [comment]
Closing this one, as #618 is the same
