### ISSUE TITLE
Difference between "Project Description" and "Comments" for a project?

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#502]
Forked from #429

**Comment by jiho** [comment]
On ~1950 projects, ~60 have description and ~15 have comments, 6 have both but project description is often just a repetition of the title.

The difference between description (called `projtype` in the db...) and comments is difficult to tell.

=> We can redefine them as we want.

I suggest to add a help text to guide users:
- _Description_: "A short paragraph describing the dataset, to make it discoverable by others in EcoTaxa and elsewhere. It should indicate **which organisms** are targeted (e.g. mesozooplankton), **where** (e.g. Bering Sea), **when** (e.g. from 2000 to 2010) and **how** (e.g. plankton net samples processed with a ZooScan) they were collected, the **scientific program** that motivated the work and **who** ran it (e.g. SCOR program coordinated by the Laboratoire d'Océanographie de Villefranche)."
- _Comments_: "Any technical, practical details that need to be shared with other users able to access this project."

Description need to be accessible from the project selection list #182 
Comments need to be accessible from the "About project page" #382

**Comment by grololo06** [comment]
Clased as not implementable, see #731 for follow-up.
