### ISSUE TITLE
Deal with deprecated taxa

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#509]
When a taxon is marked as deprecated in EcoTaxoServer, a new taxon should be designated as replacement.

In EcoTaxa then
- the taxon should be made inactive in the taxonomy filter (left column): greyed out.
- it should not appear in the autocompletion (or should appear as geyed out and unselectable) and objects cannot be dropped on it.
- in a popover that appears when the mouse is hovered on the category, add the text "This taxon is deprecated and should be replaced by thenewtaxonname."
- in the popover, add a button/link called "Change the name" that reassigns all objects in that category in that project from the old taxoID to the new taxoID + a button/link called "Create a new taxon" that adds a the new morphological taxon as a child of the proposed taxon (useful for the case of Copepoda X used to designate a certain mopho-group of Copepods)

If we encouter a case when the old taxon should be deprecated but without replacement, we will expand the spec.

**Comment by jiho** [comment]
Needed for the switch to WoRMS #454 #407

**Comment by jiho** [comment]
Currently, when a taxon is deprecated in EcoTaxoServer, it disappears from the taxonomy tree in EcoTaxa. No idea what happens when objects are classified inside it in a project (it never happened).

**Comment by grololo06** [comment]
Deprecated status apparently does not reach EcoTaxa from EcoTaxoserver

```
ecotaxoserver=# select id,name from taxonomy where taxostatus='D';
  id   |            name            
-------+----------------------------
 93638 | endodermal epithelial cell
 93639 | ectodermal epithelial cell
(2 lignes)
```

```
ecotaxa3=# select id from taxonomy where taxostatus='D';
 id 
----
(0 rows)

```

**Comment by grololo06** [comment]
Definition of deprecated: A taxon which is not valid in WoRMS and therefore should not be referenced in EcoTaxa. For a Phylo taxo, means not existing or existing with a status != accepted.

**Comment by grololo06** [comment]
See https://github.com/ecotaxa/ecotaxoserver/issues/12 for some background

**Comment by grololo06** [comment]
E.g. instead of right-click menu in the below:
![Capture d’écran de 2021-03-18 15-39-39](https://user-images.githubusercontent.com/20199778/111644650-52797080-8800-11eb-9d21-fbda0e00f5f5.png)

**Comment by grololo06** [comment]
Grey is not very visible so I chose to strike the font, which is visually annoying so users might be more eager to move to non-deprecated state.

**Comment by grololo06** [comment]
In the context of #709, present function should be able to:
- Do many changes in one go (taxon1->taxon1bis, taxon2->taxon2bis, etc...)
- Propose one _or more_ possibilities to the user 
- Tell the user what was chosen before by other users.

**Comment by picheral** [comment]
I agree.

**Comment by grololo06** [comment]
Added in 2.5.11 with maximum helpers for mass deprecation.
