### ISSUE TITLE
Format d'import/export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#52]
Actuellement, dans les fichiers d'import et d'export, la première ligne contient les titres des colonnes, la seconde le type de colonne et ensuite les données commencent.

Ceci n'est pas pratique à lire avec les fonctions classiques pour lire des tableaux, car la ligne sous les titres de colonnes est considérée comme une ligne de données. Dans le format d'import que nous avions spécifié, le type de colonne était au *dessus* du titre, pas au dessous. Il faudrait changer cela pour l'import et pour l'export.

PS: Cela signifie qu'il faut aussi changer tous nos .tsv côté zooprocess. Youpi.

**Comment by grololo06** [comment]
Est-ce toujours d'actualité ?

**Comment by jiho** [comment]
Tout à fait, et de tte façon on va changer le format d'import/export (nom des colonnes).

**Comment by moi90** [comment]
Switching the order of the first two lines will not solve the problem if there are still files with and also files without the type header. However, when using a commented preface (like BioODV #476), the type could also be included in the field description. And parsers can chose to ignore these lines because of the comment symbol (although `pandas.read_csv` only allows a single character).

**Comment by jiho** [comment]
Let us format about it for now (to my great despair).

The real solution is probably BioODV.

**Comment by grololo06** [comment]
Any small adjustment to _export_ format: add/remove/move a line, prefix columns...  would take a couple of hours. Import format impacts all the chain before so it's rather a couple of years :-)

**Comment by moi90** [comment]
What about [Darwin Core fielded text](https://dwc.tdwg.org/text/)? This is used by WORMS.

> Import format impacts all the chain before so it's rather a couple of years :-)

Not if you make it robust so it supports various varieties. E.g. pyecotaxa's `read_tsv ` supports EcoTaxa exports with and without a type header.

I think the solution to this problem has to include reference implementations in Python (and R) that read and write the data format (whatever it may then be) and that are used by EcoTaxa itself.

**Comment by jiho** [comment]
Hi @moi90 , see #476 . If we change to something it will likely be to this format, which has the advantage of being a single file, readable by ODV (which some people like), with a header that can be skipped, etc.
