### ISSUE TITLE
Standardise database fields that allow minimalistic DarwinCore Archive creation

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#520]
We should provide:
- lat, lon
- min depth, max depth
- taxonomic class
- concentration
per sample/subsample.

That means that the required fields should be mapped to DwC/BODC terms and made as explicit fields in the database

- lat = `decimalLatitude` http://vocab.nerc.ac.uk/collection/P01/current/ALATZZ01/
- lon = `decimalLongitude` http://vocab.nerc.ac.uk/collection/P01/current/ALONZZ01/
- depth: `maximumDepthInMeters`, `minimumDepthInMeters` 
- taxonomic class = `scientificNameID` and `sciencificName`
- subsampling coef = http://vocab.nerc.ac.uk/collection/P01/current/SSAMPC01/1/ no unit
- volume sampled = http://vocab.nerc.ac.uk/collection/P01/current/VOLWBSMP/ in m3

The last 2 are not explicit database fields, the first 3 are at object level when then most often should be elsewhere.

This this would allow to compute concentration, wich is  http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL01/ with unit http://vocab.nerc.ac.uk/collection/P06/current/UPMM/

Concentration per sample/subsample is to be computed as (in pseudo code)

```
unit concentration of organism in sea water [#/m3] = 1 / subsampling coef / volume sampled [m3]
concentration per sample/subsample [#/m3] = group_by(sample/subsample ID) then sum(unit concentration)
```

**Comment by jiho** [comment]
It is still be be discussed with VLIZ if this is indeed the minimum set of metadata that allows an import on EMODnet's side.

**Comment by grololo06** [comment]
I'd need to know how to get the data `subsampling rate` and `volume sampled`, at least for all the projects referenced in #426.

**Comment by jiho** [comment]
Here is the mapping (so far, to be completed)

- `object > lat`, `object > lon`
- `object > depth_min`, `object_depth_max`
- taxonomic class = we define it
- subsampling rate
    - for zooscan: `acquisition > sub_part `
    - for flowcam:
    - for zoocam:
    - for planktoscope:
    - for IFCB:
    - for ISIIS:
    - for UVP5: 1
- volume sampled
    - for zooscan: `sample > tot_vol`
    - for flowcam:
    - for zoocam:
    - for planktoscope:
    - for IFCB:
    - for ISIIS:
    - for UVP5: not accessible currently

**Comment by fabienlombard** [comment]
well this gonna be complicated, the methodology is quite complicated for the flowcam (and so-far at least 3 different methodology have been used). I have this in different codes, but I think this could be really great to meet together and see how to harmonize all this. But all in one for flowcam  vol sampled is in sample_comment_or_volume and to calculate the subsampling you need to combine  raw_image_total process_nb_images sample_volconc (volume of sample in the collector of the net; this latter may contains additional calculation before being filled in ecotaxa if several concentrations steps have been used)  acq_fluid_volume_imaged

calculate the volume processed Volume_Imaged_Processed= (fluidimaged/ raw_image_total)* min(raw_image_total,process_nb_images);
    
concentrations= abundances*  Volconc./(Volume_Imaged_Processed.*comment_or_volume)

I have such kind of methodology for every instrument.... and sometimes different between campaigns depending on the cruise and exact protocol used (yes this is boring)

and before doing so we need to be sure that all volumes units are the same (and correcting it beforehand, interpreting m3 as in mL don't give you a chance to get correct results)

**Comment by grololo06** [comment]
I was so afraid that it could be simple :)
First quick step I'd need a validity interval for these data in order to filter them out, as I strongly suspect that the 9999 here: https://ecotaxa.obs-vlfr.fr/objectdetails/44721466?w=848&h=862 does not reflect the reality of the sampling operation.
![Capture d’écran de 2020-11-08 08-05-06](https://user-images.githubusercontent.com/20199778/98459235-3b16e080-2199-11eb-8398-75cebabb86e5.png)

**Comment by fabienlombard** [comment]
99999 means missing values


Yes « na » was too simple (but not compatible with zooprocess)

**Comment by jiho** [comment]
Superseeded by various new issues, including #621 , #616 .
