### ISSUE TITLE
Bug : problème avec la définition du preset

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_dev#523]
Quand on clique sur "Pick from others projects" dans edit settings d'un projet, l'attente de l'ouverture de la fenêtre peut être longue.
Une fois apparue, que l'on clique sur un preset ou qu'on l'alimente avec d'autres catégories, qu'on fait save et qu'on retourne à notre projet, on peut parfois constater que le preset n'a pas été enregistré. En retournant à edit settings, on peut alors voir un preset vide alors qu'on vient de l'écrire et qu'on a fait save.

**Comment by Kikouliou** [comment]
Aussi, la liste n'apparaît plus dans l'ordre alphabétique.

**Comment by grololo06** [comment]
Hello, la liste est dans l'ordre alphabétique il me semble. Il y a les chiffres et caractères spéciaux en premier, mais après je vois bien "Akko" et ainsi de suite.

**Comment by grololo06** [comment]
La fenêtre met (encore +) du temps à apparaître car tu es admin, donc potentiellement _tous_ les projets sont là. La lenteur supplémentaire est dûe à #435, il y a une étape de transfert de données ajoutée donc c'est plus lent.

**Comment by grololo06** [comment]
Pour le problème du non-enregistrement, il faut caractériser le "parfois", donc la prochaine fois que ça arrive, essayer de se souvenir des actions faites récemment. Ou le noter quelque part avec l'heure pour pouvoir diagnostiquer à partir des fichiers journaux. Il est possible aussi que quelqu'un d'autre ait fait "sauver" au même moment et écrase tes propres modifications. Ou toi-même dans une autre fenêtre.

**Comment by grololo06** [comment]
Ah je crois que je l'ai aussi sur mon PC. Pas besoin de chercher...

**Comment by grololo06** [comment]
Corrigé en 2.4.6 pour le problème principal de perte de données.

**Comment by jiho** [comment]
Pb non réglé.

**Comment by grololo06** [comment]
Le raccourci "Edit Privileges Only" cause le retour du problème. 
En modifiant les privilèges en bas de la page principale rien n'est perdu.
Le raccourci a été invalidé en production en attendant:

```
{% else %}
    <h3>Edit project # {{ data.projid }} -
        <a href="/prj/editpriv**ZZZ**/{{ data.projid }}" style="font-size: medium;"
           class="btn btn-xs btn-primary">Edit privileges only</a></h3>
{% endif %}

```

**Comment by grololo06** [comment]
Regression fixed in 2.5.1.
