### ISSUE TITLE
Allow to reorder and add items to free fields mapping

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#526]
Many projects have similar but not exactly identical mappings for free fields. Having an exact match is desirable for several things (collections #519, prediction etc.).

Add an item (button, section) to the "Edit project settings" page that allows to:
- reorder mapping, ideally graphically with a drag and drop UI; the content of the corresponding fields is then moved
- add an element to the mapping; the corresponding db field is filled with NULL
- match the mapping of a target project; the fields present in the target project are added to the source project; the fields present in the source project only are moved to the end

This applies to all mapping (obj, pro, acq, smp).

This is only available from project level when the project is not in any collection.

Upon future imports, the columns in the imported file are moved to the appropriate fields within the new mapping = their order does not matter, only their name does (which should already be the case, hopefully).

**Comment by grololo06** [comment]
This "mapping" has never been exposed to users so far and that's good. They see their data as fixed columns + free ones with names that they choose.
If what you describe is needed in collections, then please add a dedicated paragraph in the corresponding issue, same for any other function.

**Comment by jiho** [comment]
No this is needed at project-level because at collection-level (specification in progress), only the free columns that are in the same order across all projects of the collection will be retained.

From the user's point of view, this function is to be labelled "Reorder or add columns"; the internals of how it is coded indeed does not matter.

Another possibility is to implement this during the creation of a collection: if all projects in the collection are not in any other collection, reorder their columns to match as best as possible, taking one project as reference.
However, I was thinking that is is better to have independent pieces of functionality that fit together. Users may want to reorder for other reasons (export outside of collections, etc.).

**Comment by grololo06** [comment]
OK let's keep on hold until Collections specs.

**Comment by grololo06** [comment]
OK decision made 25/03/2021: Not to show the users their field order. But allow to add a free column during collection creation to have the same column set in all projects of a collection.
