### ISSUE TITLE
Add a meanfull message when loading an ancient project

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#529]
The display of an ancient project (not seen for a while) takes ages. There should be a message indicating the reason of the long delay in addition to the actual wheel.

**Comment by grololo06** [comment]
It's not only old projects, it's also recent ones when the server is loaded. In 2.5.1 there will be a wait indicator during load. Not so reliable as we don't know the time it takes before finishing the job, but based on a measure of time for a small subset (sample :)) of the data to come.

**Comment by grololo06** [comment]
Fixed in 2.5.1.
