### ISSUE TITLE
Rappel sur le nom du projet situé sur le serveur utilisé pour des imports

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_dev#530]
Lorsque nous faisons un import (import d'un projet ou update metadata), nous avons ce message :

![image](https://user-images.githubusercontent.com/33952113/98663840-df3f8980-2349-11eb-8bdb-d9e4966941fb.png)

Il serait pratique d'avoir un rappel sur le nom du projet situé sur le serveur que l'on a utilisé pour l'import

**Comment by grololo06** [comment]
I.e. ce qui permet de différencier les opérations d'import entre elles, typiquement la source d'import.

**Comment by grololo06** [comment]
Fixed in 2.5.13. The reminder would deserve more highlighting maybe.
