### ISSUE TITLE
Advanced sample selection does not work in a project

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#538]
Steps to reproduce
- connect to https://ecotaxa.obs-vlfr.fr/prj/1447
- select other filters
- click sample > advanced 
- tick some samples
- click Apply

Result: no sample is selected in the main window.

Would it be related to the spaces in the sample names?

**Comment by grololo06** [comment]
Yep good guess, will be fixed in 2.5.1

**Comment by grololo06** [comment]
OK verified in 2.5.1.
