### ISSUE TITLE
EXPORT : include task log in the ZIP

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#539]
it would be great if the zip contained the log files so that we can review locally,
or at least a link to the online task log – or just the task number in the zip-filename?

**Comment by jiho** [comment]
I think including the log as a text file is easy and useful indeed + more permanent than a link to the online version which gets cleaned.

**Comment by grololo06** [comment]
Only for the zip-producing types (DOI and Backup)

**Comment by grololo06** [comment]
Fixed in 2.5.9.
