### ISSUE TITLE
Change taxonomy API endpoints names

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#557]
Most other endpoints are singular when querying a single item and `***_set` when querying several.

For taxonomy, taxon is the singular form, taxa is plural.

So
- `taxa/{taxon_id}` should be `taxon/{taxon_id}`
- `taxa_set/query` should be `taxon_set/query`
- `taxa/search` shoud be `taxon_set/search`

An alternative would be to use the singular form as now and the plural form instead of the `***_set` form (i.e. taxon, taxa here, and object/objects rather than object/object_set etc.). But it may be more prone to mistakes.

**Comment by grololo06** [comment]
Fixed in 2.5.2.
