### ISSUE TITLE
Homogenise API endpoints names

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#558]
We have somewhat a mix of singular, plural and `***_set` forms now:
- user**s**
- collection**s**
- project**s**/project_set
- sample/sample_set
- acquisition/acquisition_set
- process/process_set
- object/object_set
- tax**a**/taxa_set (but see #557)
- tasks

Some accept/return a single item, others accept/return several.

Two choices
1. singular / plural
2. singular / ***_set

**Comment by jiho** [comment]
I think I prefer singular/plural and replacing `search` by filter (which matches the terminology in the UI). Examples:

users
users/filter (or search, it kind of fits here)
user/me
user/{user_id}

collection/create
collections/filter

projects/filter
project/create
project/{project_id}

samples/update
sample/{sample_id}

objects/{project_id}/filter
objects/{project_id}/reset_to_predicted
objects/update
object/{object_id}

taxa/filter
taxon/{taxon_id}
taxa/query

**Comment by grololo06** [comment]
Devs have the online doc, they don't really care about names.
