### ISSUE TITLE
Any user managing any project should be able to create a taxon

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#562]
Clean follow-up of #321 
I think it's to discuss, as:
- lots of people are managers on at least 1 project
- if we add the possibility to _create_ a taxon and e.g. the user makes a typo, he/she cannot correct it as he/she doesn't have "Project Creator" role

So it looks like creating an inconsistency or risk somewhere.

**Comment by jiho** [comment]
Confirmed: anyone being manager on any project can create a taxon

**Comment by grololo06** [comment]
Fixed in 2.5.11
