### ISSUE TITLE
Add "Save" button at the top of the project settings page

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#564]
To make it easy to validate the settings near the top, add a "Save" button at the right of the title, like so

<img width="1626" alt="Screenshot 2021-01-16 at 10 53 20" src="https://user-images.githubusercontent.com/18445/104808856-3c900500-57e9-11eb-8d05-88ba16371d0c.png">

**Comment by grololo06** [comment]
Fixed in 2.5.2.
