### ISSUE TITLE
Add a Contact person per project

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#565]
Need to be a **single** person and a project **manager**.

Several choices for implementation:
1. a separate setting, above the user privileges section, with a select box for users. This person is made into a new role and this role has the same privileges as the other project managers. Add a help text next to it stating "This user is displayed in the project table and serves as the contact person for other users and EcoTaxa's managers. This user is automatically a manager of the project"
2. a new role to be chosen in the privileges table (in the select drop down), but making sure that only one of the users can be selected for this role. In terms of background implementation this can mean : give it manager role and add a toggle "contact" elsewhere, or make it a separate role. Add a help text with "Viewers can view the project even when it is private; the project is listed in their project list. Annotators can classify objects. Managers can import and delete data, as well as change project settings. The contact person has manager privileges, is displayed in the project table and serve as the contact person for other users and EcoTaxa's managers."
2. a column of radio buttons in the user privileges table, called "Contact" (before "Delete" but looking similar); inactive for non managers, active for managers; because these are radio buttons, only one can be ticked at a time. Need to make sure that if someone is contact and is demoted from manager role or deleted, someone else is named as contact. Same help text as above.

**Comment by grololo06** [comment]
Fixed in 2.5.2.
