### ISSUE TITLE
Calculate and display percentage of sorting per profile

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa_dev#572]
In some cases, not the entire project needs sorting or is sorted. There is no way to see which profiles are sorted to what extent. Add an indicator in the advanced sample selection and maybe also allow filtering on this value.

<img width="1289" alt="Bildschirmfoto 2021-01-21 um 13 21 11" src="https://user-images.githubusercontent.com/6485104/105350623-bceca680-5beb-11eb-85c2-e85e9cf17eda.png">

**Comment by picheral** [comment]
This is the objective of the #382 issue.

**Comment by grololo06** [comment]
I'm not aware of "sorted" property for samples aka profiles. @rkiko can you please expand?

**Comment by rkiko** [comment]
NO, it needs to be calculated per profile. E.g. a profile can have 1000 images, sometimes this is fully sorted (or validated, all in green), sometimes not. We can see what percentage in a project is validated, predicted, dubious, but not per profile. We need this info also per profile.

**Comment by grololo06** [comment]
In order to save dev. time, it's been decided to integrate this information in About Project, so, for the 'short term', in order to get presently needed information, you will have to open another tab in the navigator and choose.

**Comment by jiho** [comment]
And (even though it is not practical) this info is computed by selecting a single sample in the sample filter and looking at the numbers and progress bar at the top of the page.
