### ISSUE TITLE
Après validation de la deuxième page, la première page n'est pas montrée

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_dev#576]
Je travaille par page de 1000, et quand j'ai 1400 vignettes (par ex), il m'arrive parfois de commencer par la page 2 (les 400 vignettes donc). Une fois la page 2 validée, je dois normalement retomber sur la page 1 avec mes 1000 vignettes restantes.
Après mon ctrl+s sur ma page 2, voici ce qui est apparu :

![image](https://user-images.githubusercontent.com/33952113/105467700-f544c100-5c8d-11eb-9775-152bc19304e3.png)

Il me dit page 2/1, me dit que je suis sur la page 1 et me montre pas mes vignettes

**Comment by grololo06** [comment]
Is due to API-fication of manual classification page, most probably this commented-out part in project/main.py:
```

    # if pageoffset >= pagecount:
    #     pageoffset = pagecount - 1
    #     if pageoffset < 0:
    #         pageoffset = 0

```

**Comment by grololo06** [comment]
Fixed in 2.5.3.
