### ISSUE TITLE
Allow to remap categories before export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#577]
Use case: half the samples are sorted with a given level of detail (e.g. copepods in sub-categories: Calanoida, Harpaticoida), the other half is sorted with less detail (e.g. copepods all in Copepoda). I want to export a dataset in summary form (numbers/concentration per category) homogeneously sorted = where 0 means that no organism of that category was ever found. If I export it as it is, for half of the samples I will get 0 for Calanoida not because there were 0 but because they were never looked for.
The only solution is to regroup all subcategories of Copepods into "Copepoda" and export only this. One solution to do this is to have, before export and optionally, the possibility to remap categories following this design #138 .

This is a typical scenario for time series exports, exports to DwCA with 0 in concentrations, etc.

**Comment by jiho** [comment]
This setting should be remembered per project and per collection (a project within a collection can have a different setting compared to the collection it is in since the level of homogeneous detail for this project could be higher than for the whole collection).

**Comment by jiho** [comment]
For this particular use case, we could limit the choice of categories to remap to to the lineage of the current category, to not allow people to shoot themselves in the foot.

It is to be considered/debated because it may not be appropriate all the time (e.g. remapping "Fiber" to "Trichodesmium" because we know that they are actually this, or the opposite).

**Comment by grololo06** [comment]
I guess the interface will be #138 with the constraints exposed.

**Comment by grololo06** [comment]
Was split to fit per-page PM model.
