### ISSUE TITLE
Export abundances / concentrations of 0 in summary (and DwCA) export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#578]
If a project is homogeneously sorted, the absence of a category in a given sample is an information. This information is not explicitly representable in the regular export but:
- it could be in the summary export
- it could be in the DwCA export

From Ruben Lopez, regarding DwCA
> Indeed, an occurrence has been generally accepted as a presence or that is my understanding as well. However we are trying to expand from there both in OBIS and EMODnet Biology encouraged by an increasing demand of absence data.
OBIS includes in their OBIS-ENV data format a DwC field called occurrenceStatus that can be either "present" or "absent". If the occurrenceStatus = "absent" no errors should emerge for a concentration (or any other biological measurement) = 0.

Do we make those 0 appear?

**Comment by grololo06** [comment]
I don't get in full, there are 900K+ taxa in Worms tree, shall we emit a "not there" record for all of them except the few ones in the export?

**Comment by jiho** [comment]
Sorry it was not clear.

- Build a list of taxa from all those with at least 1 object in the project
- Compute abundance/concentration per sample for each taxon
- When no image is classified in a taxon*sample combination, output 0

**Comment by grololo06** [comment]
I assume that "project" in below is in fact a collection, feel free to tell me if not the case.

> Sorry it was not clear.
> 
>     * Build a list of taxa from all those with at least 1 object in the project
> 
>     * Compute abundance/concentration per sample for each taxon
> 
>     * When no image is classified in a taxon*sample combination, output 0

**Comment by jiho** [comment]
> I assume that "project" in below is in fact a collection, feel free to tell me if not the case.

Project or collection, depending on which export. The summary export is available at project level and outputing 0 there would make sense. But this export does not compute concentrations yet.

**Comment by grololo06** [comment]
Closing because transversal issues end up in never-ending stories like #435
