### ISSUE TITLE
List of users in Privileges section is incorrect

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#580]
https://ecotaxa.obs-vlfr.fr/prj/edit/187
https://ecotaxa.obs-vlfr.fr/prj/edit/189

Those were projects with a lot of students as Annotator. Currently they are all listed with the same name...

This seems to be a display problem since the userids are all different in the database

```
SELECT projid,member,name FROM 
(SELECT * FROM projectspriv WHERE projid=187) lhs
LEFT JOIN users AS rhs ON lhs.member=rhs.id;
```

**Comment by grololo06** [comment]
Adding active column to the query:
```
SELECT projid,member,name,active FROM 
(SELECT * FROM projectspriv WHERE projid=187) lhs
LEFT JOIN users AS rhs ON lhs.member=rhs.id
```
-> Inactive users are shown as the first user in the dropdown as they are not listed there.

**Comment by grololo06** [comment]
Hotfixed. Be sure to reload without cache (CTRL+reload on Firefox) otherwise the bloody browser remembers previous values.
