### ISSUE TITLE
Adding a new manager is complicated by the necessity to add a contact person

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#581]
Use case: I want to add a new person as manager to make it the contact person.

1. Add that person with manager permission
2. Save
3. Get the message that a contact person needs to be designated but the new manager seems to be present
4. I pick the new manager as contact
5. Save
6. The manager disappeared

In fact, I need to pick a contact person, then add the manager, then change the contact. It is a bit difficult to understand.

However, this is kind of unavoidable to require the contact person.

The part that could be considered as a "bug" is that, upon adding the manager while not selecting a contact, the new manager seems to appear (while it is not actually saved).

**Comment by jiho** [comment]
Marc, is that your experience (while adding M-H Forget)?

**Comment by grololo06** [comment]
Hofixed.
