### ISSUE TITLE
Freeze and version dataset upon release to a public database

### ISSUE THREAD

**Issue by rkiko** [ecotaxa/ecotaxa_dev#585]
If a dataset is submitted to a public archive, a version of the dataset should be frozen on ecotaxa. Otherwise, no further sorting on the dataset should be allowed to avoid divergence from the published version.

**Comment by grololo06** [comment]
Make sense IMHO. Even if (for EMODnet) we send a snapshot of the data, there is a back-link to EcoTaxa which should be permanent and immutable. 
So , it's linked with archival topics and read-only state of data .

**Comment by picheral** [comment]
Je pense que ce n'est pas un back link (retour du projet à un état donné) mais plutôt une possibilité de visualiser le projet tel qu'il était à une date donnée.

**Comment by jiho** [comment]
On a toujours dit qu'EcoTaxa était un outil de travail, pas d'archivage. L'export vers EMODnet est justement une façon de "freezer" le jeu de données sur une BDD externe. L'export "DOI" ou "archive" permettent de le mettre, avec les images, sur une base de fichiers genre SeaNoe ou Pangea.

Donc je suis moyen pour sauf si c'est extrêmement cheap à coder.

**Comment by grololo06** [comment]
As stated on the home page: "Disclaimer: The managers of the EcoTaxa application are not responsible for the safekeeping of the images and associated data it hosts, even if they make their best to keep the application stable and secure."
So indeed, keeping forever a reference to a read-only dataset is not in the app scope.
However, by using present & work in progress functions, a manager can achieve a similar result.
- Subset (100% of) what you want to "freeze" (with images)
- Merge into a fresh project
- Set the fresh project to "ExploreOnly" and proper licence (not fully protecting the data as I'm writing, see #486)
In Q2 2021, there should be a mechanism to avoid image duplication in EcoTaxa, so this operation would be "cheap" from data volume point of view.
