### ISSUE TITLE
Project update via API fails in some specific case(s)

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#596]
For example
GET projects/185
change comments to "toto"
PUT projects/185 with the new information
The reply is
1   body, contact, usercreationdate invalid type; expected datetime, string, bytes, int or float
2 body, contact, usercreationreason                                            str type expected

usercreationdate and usercreationreason for contact (myself) are NULL.

The solution is probably to set 01-01-2017 in usercreationdate and an empty string in usercreationreason for those where this is not set.

**Comment by jiho** [comment]
NB: changed the contact to someone else to be able to continue tests.

This highlights that an empty creation date or reason is problematic for the contact, but not for the other users (because, while I am not the contact anymore, I am still a manager), which is weird.

In that case the fix may rather be to accept NULL in both the managers/annotators/users AND in the contact.

**Comment by jiho** [comment]
Over 1058 users we have
- 503 empty creation dates
- 455 NULL and 346 empty strings ("") in creation reason

**Comment by grololo06** [comment]
The validator is the same for users in various lists and for the contact, so indeed this is weird.
This mechanism (GET+PUT) is used in the python GUI code with no special trick, so I guess that R json mapping is the problem.
I would need to see the sent PUT JSON string, to be sure.

**Comment by jiho** [comment]
I've changed back the contact to someone without `usercreationdate` and `usercreationreason`, to test.

Here is the relevant bit of the json that is returned by the GET

```
"contact":{"id":5,"email":"amanda.elineau@obs-vlfr.fr","name":"Amanda Elineau",
"organisation":"Sea Institute of Villefranche sur Mer - IMEV",
"active":true,"country":"France","usercreationdate":null,"usercreationreason":null}
```

Here is what it looks like after being parsed into R and reconverted into json

```
"contact":{"id":5,"email":"amanda.elineau@obs-vlfr.fr","name":"Amanda Elineau",
"organisation":"Sea Institute of Villefranche sur Mer - IMEV",
"active":true,"country":"France","usercreationdate":{},"usercreationreason":{}}
```

So I am guessing it is an R problem indeed, and that the `{}` are incorrect.

**Comment by jiho** [comment]
And indeed, with `jsonlite::toJSON(..., null="null")` it works just fine. Closing.
