### ISSUE TITLE
Add concentrations in summary export

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#604]
From #578 
To decide: how/what in practice. Common cases include "no data for calculation, in any entity of for just a few of them".
So far the summary export is a simple "group by" query of the objects, no section of any kind.

**Comment by grololo06** [comment]
More specs:
 - Export abundances / concentrations in summary export 
 - Reuse the code/algorithms presently EMODnet.py https://github.com/ecotaxa/ecotaxa_back/blob/4fa0cbaaa1b3d7b35699111703f47dc042dea61f/py/API_operations/exports/EMODnet.py#L427
+ Add the 0 - concentration calculations from #578

**Comment by picheral** [comment]
The initial choice for EcoTaxa was to NEVER process abundances. If we now have this possibility for some projects, it makes sense to offer this calculation in the Export summary too.

**Comment by jiho** [comment]
Super-seeded by #616, closing.
