### ISSUE TITLE
EMODnet export using instrument BODC vocabulary

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#624]
As of today, the code only instruments are "bongo" and "multinet"

So now that our instruments are properly registered, better to use them.
 
See https://github.com/ecotaxa/ecotaxa_dev/issues/264#issuecomment-768339764

Note that sampling instrument != imaging instrument

**Comment by jiho** [comment]
> Note that sampling instrument != imaging instrument

Indeed, the instruments that were registered (in #264) are imaging instruments.

Sampling instrument will not be normalised (for now) in EcoTaxa and should therefore not be included in dwca export.
IMHO, the solution for this (and others) is #521 .
