### ISSUE TITLE
Include stable provenance information in the dwca export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#631]
After a dataset is published to OBIS (EMODnet biol etc.), it would be important that people using that dataset can come back the the data in EcoTaxa (i.e. the collection that was exported). This will be required by the BlueCloud project to be able to run more detailed queries on this data through the API.

This requires:
- [ ] a unique, persistent identifier for collections
- [ ] a field in dwca to store this provenance info (source url, or instance url + unique id)
- [ ] a switch at collection level to track which are published to OBIS and warn when the manager tries to delete them

The second part is waiting for specifications from Lennert Shepers at VLIZ. Once this is known, decisions can be taken regarding the format for the identifier (and this issue probably split into several 😉 )

**Comment by LennertSchepers** [comment]
Could you tag/assign me to this issue? (apparently I can not do this myself, even not in this message)

**Comment by grololo06** [comment]
Linked with #585

**Comment by grololo06** [comment]
In this introduction to EML: https://eml.ecoinformatics.org/eml-ecological-metadata-language.html the packageId is defined as:
```
<?xml version="1.0"?>
<eml:eml
    packageId="doi:10.xxxx/eml.1.1" system="https://doi.org"
```
but apparently other systems are OK too.
Anyway so far the code generates the same UUID for all eml which is bad.

**Comment by grololo06** [comment]
EML generating code is now fixed, but the code does not invent unique IDs so we're left with the global unicity/referencing problem.

**Comment by grololo06** [comment]
Hello, let's go for the <additionalMetadata> tag.

**Comment by grololo06** [comment]
After digging a bit more, it looks like we should not use <additionalMetadata> because I found it **added** into a formerly submitted (by us) dataset, see the DwCa file here: https://obis.org/dataset/e8f6f42e-0e33-4382-9998-9a178eac3191 My conclusion is that this part "belongs" to GBIF, which makes sense.

**Comment by LennertSchepers** [comment]
Hi @grololo06 

**1. adding a link to the datasets on the ecotaxa platform (e.g. https://ecotaxa.obs-vlfr.fr/prj/397)**

My understanding is that IPT is developed by GBIF and uses an extended eml profile with some specific metadata fields in the `<additionalMetadata>`. This doesn't mean that all metadata in this `<additionalMetadata><gbif>` section must be related to GBIF, but it's just a placeholder where we can/should put metadata for IPT.

Also the EurOBIS, OBIS and EMODnet Biology links do not 'belong' to GBIF ([example](http://ipt.vliz.be/eurobis/eml.do?r=dasshdt00000071&v=1.1)), but when inserting them at this location makes that they are visible in the html under 'external data' for example http://ipt.vliz.be/eurobis/resource?r=dasshdt00000071.

Therefore we suggest to also include a link as <https://ecotaxa.obs-vlfr.fr/prj/397> at the same location.
`<additionalMetadata><metadata><gbif><physical><distribution><online><url>`

**2. offer a way to identify Ecotaxa datasets from the other EurOBIS datasets**

We suggest to add Ecotaxa as <metadataProvider> in the metadata, see the same example [here](http://ipt.vliz.be/eurobis/eml.do?r=dasshdt00000071&v=1.1). This is consistent with our current workflow. Currently Ecotaxa is mentioned as a Keyword?
