### ISSUE TITLE
Backup export : export table only

### ISSUE THREAD

**Issue by Elineau** [ecotaxa/ecotaxa_dev#633]
Add the "img_file_name" column in the export table

**Comment by grololo06** [comment]
Note: Backup export should be roundtrip tested: create a project P1 -> load -> backup export -> import into project P2 -> compare content of P1 and P2

**Comment by grololo06** [comment]
To be consistent with export_backup_with images, there will be as well `img_rank` column **and** one line per image, please get back to me in case it's not OK.

**Comment by grololo06** [comment]
Fixed in 2.5.9.
