### ISSUE TITLE
Permission to create category is not correctly reflected in the message/link in the taxo filter

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#637]
Currently, project creators can create categories (but see #562 ). This is a global permission/role. However, the link in the taxonomy filter depends on the status of the user in the project.

Fabien in a project where he is not manager
![image (6)](https://user-images.githubusercontent.com/18445/109848065-28488000-7c50-11eb-9831-503c417d8497.png)

Fabien in a project where he is manager
![image (7)](https://user-images.githubusercontent.com/18445/109848070-2aaada00-7c50-11eb-81f4-314d3b414578.png)

The expected behaviour is that it should not depend on the project but only on the user.

**Comment by grololo06** [comment]
Fixed in 2.5.11
