### ISSUE TITLE
Amelioration page prédiction

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#65]
Indiquer par un titre : DESTINATION (predicted) categories... pour la première liste.
Indiquer par un titre : SOURCE catégories... pour la seconde liste ajoutée dans la version 1.2 et qui sert à re-prédire.
Cela sera plus explicite pour les utilisateurs.

**Comment by picheral** [comment]
Fera partie de la refonte des pages CLASSIF

**Comment by grololo06** [comment]
Fixed in 2.5.13.
