### ISSUE TITLE
L'assignation en dubious empêche la sauvegarde de changements

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_dev#652]
Ce que j'ai fait : 
J'ai assigné des vignettes sur une page de vignettes prédites, puis parmi ces dernières j'ai voulu en assigner une en dubious : j'ai cliqué sur l’œil de la vignette, j'ai entré ma catégorie dans "Set a new classification : " puis sur "Save as dubious". Je me retrouve donc sur une page de vignettes prédites avec certaines assignées (couleur verte, écriture rouge + une en orange, écriture noire). J'ai fais ctrl+S.

Ce que j'ai eu :

![image](https://user-images.githubusercontent.com/33952113/114681849-d5fa8480-9d0e-11eb-8b12-6af0bba64f92.png)

Aucune sauvegarde sauf la sauvegarde de ma vignette en dubious 

Ce que j'attendais : 
Une sauvegarde de mes vignettes assignées et leur passage en statut validé.

**Comment by grololo06** [comment]
De mes propres essais, le problème est un petit peu plus général. Les boutons "Save as dubious" et "Save as validated" de la page "object details" entraînent tous les deux une invalidation silencieuse des changements en cours.

**Comment by grololo06** [comment]
Le bouton "Set Selection Dubious" en bas du panneau droit fonctionne, i.e. il passe en "dubious" la sélection courante _et sauve aussi tous les changements_.

**Comment by grololo06** [comment]
Corrigé en 2.5.7.
