### ISSUE TITLE
Short URL in DwC collections.

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#660]
We need to include a short(er) URL as permalink to Collections, as a new DB column. 

The data for present collections should be:

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6505
Plankton community in WP2 net (200µm), Point B, Villefranche-sur-Mer, France
point-b-wp2-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6506
Plankton community in Régent (680µm) net, Point B, Villefranche-sur-Mer, France
point-b-regent-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6507
Plankton community in Juday-Bogorov (330µm) net, Point B, Villefranche-sur-Mer, France
point-b-juday-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6508
Plankton community in WP2 net (200µm), DYFAMED point, Ligurian Sea, France
dyfamed-wp2-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6510
Plankton community in Bongo net, MOOSE-GE cruises, North-Western Mediterranean Sea
moose-ge-bongo-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6511
Plankton community in WP2 net (200µm), PNMIR cruises, Parc Naturel Marin d'Iroise, France
pnmi-wp2-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6512
Occurrence of Eukaryotes in the size fraction >300 micrometres, collected worldwide during the Tara Oceans expedition (2009-2013) using a Bongo net and analysed on a ZooScan imaging platform
tara-oceans-bongo-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6513
Occurrence of Eukaryotes in the size fraction >300 micrometres, collected worldwide during the Tara Oceans expedition (2009-2013) using a Multinet and analysed on a ZooScan imaging platform
tara-oceans-multinet-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6514
Occurrence of Eukaryotes in the size fraction >680 micrometres, collected worldwide during the Tara Oceans expedition (2009-2013) using a Régent net and analysed on a ZooScan imaging platform
tara-oceans-regent-zooscan

https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6515
Occurrence of Eukaryotes in the size fraction >200 micrometres, collected worldwide during the Tara Oceans expedition (2009-2013) using a WPII net and analysed on a ZooScan imaging platform.
tara-oceans-wp2-zooscan

**Comment by LennertSchepers** [comment]
Could you give an example of the full link?
Will this be the short title added to https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q= or https://ecotaxa.obs-vlfr.fr/api/collections/short-title?

**Comment by grololo06** [comment]
Hi, let's go for e.g. https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=point-b-wp2-zooscan

**Comment by LennertSchepers** [comment]
| Dataset | Link added|
| ------------- | ------------- |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6505 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=point-b-wp2-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6506 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=point-b-regent-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6507 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=point-b-juday-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6508 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=dyfamed-wp2-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6510 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=moose-ge-bongo-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6511 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=pnmi-wp2-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6512 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=tara-oceans-bongo-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6513 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=tara-oceans-multinet-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6514 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=tara-oceans-regent-zooscan |
| https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6515 | https://ecotaxa.obs-vlfr.fr/api/collections/by_short_title?q=tara-oceans-wp2-zooscan |

**Comment by jiho** [comment]
👍

**Comment by grololo06** [comment]
All links work fine (and are public) after application upgrade to 2.5.7
