### ISSUE TITLE
"Use previous learning set" label is misleading in classification 

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#665]
As it's 'only' reusing the same *projects* for building the learning set, as a new random sampling will be done.

**Comment by jiho** [comment]
But the "random" sampling is actually not random, isn't it?

And the random sampling comes into play only when the users selects a learning **source** (which may be a better term than learning **set**) that has more than 5000 objects in at least one class, or changes the default number to something smaller than 5000.

**Comment by grololo06** [comment]
Whatever happens at next step, this button just saves the selection of projects so it should be e.g. "Use previous projects". Eventually it should not exist at all, as the page contains a list of projects, which could be pre-selected using the same information. #65 or #517 for other usability problems of this wizard-like set of pages.

**Comment by grololo06** [comment]
Fixed in 2.5.13.
