### ISSUE TITLE
Inform user that tasks cannot be killed

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#674]
With the new organisation of tasks (jobs) that run on the backend while being launched from the front end, it is difficult to kill a running task.
In addition, for data consistency purposes, killing as task that leads to writes in the DB (e.g. imports) should remove all those writes, leaving no trace that the task was even run, which is even harder.

Hence it is now impossible to kill tasks (jobs). 

The user need to be informed. Next to the last button before running the task (import, export, etc.) add a note:

"Once a task is launched, for consistency and performance reasons, it cannot be killed. You must wait for it to finish. Please make sure that it you chose the correct options above."

**Comment by grololo06** [comment]
Tasks _can_ be killed by clicking the "Clean task data" button. The task will die next time it tries to access its private data, which is gone.
