### ISSUE TITLE
Some exported images have the same filename inside an object

### ISSUE THREAD

**Issue by moi90** [ecotaxa/ecotaxa_dev#679]
When exporting multiple images per object, they all are stored with the exact same filename inside the zip file. Because image files inside the archive are referenced by filename in the ecotaxa_*.tsv, whatever was last added to the archive is used (although the archive contains both). This will also be a problem for the re-import, as EcoTaxa first unzips the whole archive, thus overwriting each image with the other.

This can be observed in task_43104_export_3945_20210506_1159.zip (if the file is still present).

**Comment by grololo06** [comment]
Hello, you mean e.g. the ones between ** ?
```
     1020  2021-01-21 17:59   solace_047/13/20201224-194320_03_2.png
      895  2021-01-21 17:59   solace_047/13/20201224-194320_03_2.png
     1707  2021-01-21 17:59   solace_047/13/20201224-194320_04_1.png
     1655  2021-01-21 17:59   **solace_047/13/20201224-194320_04_1.png**
      827  2021-01-21 17:59   solace_047/13/20201224-194320_05_1.png
      699  2021-01-21 17:59   solace_047/13/20201224-194320_05_1.png
     2693  2021-01-21 17:59   solace_047/13/20201224-194321_01_1.png
     2616  2021-01-21 17:59   solace_047/13/20201224-194321_01_1.png

```

**Comment by moi90** [comment]
> Hello, you mean e.g. the one between ** ?

What do you mean? In the example, *every* object has two identically named but different image files. This should never happen. As a remedy, the filename could also include the image rank (at least if multiple ranks are used).

**Comment by grololo06** [comment]
Looks linked to UVP6 specific code, the 'vignette' and backup have the same name in image DB table.

**Comment by moi90** [comment]
It makes sense because both versions are derived from the same original image, right?

But how do we resolve this problem? With these duplicated filenames, the export is next to worthless.

I see two possibilities:
- Either, the rank could be appended to the filename unconditionally. (That would be ugly and unnecessary in most cases.)
- Or, you keep track of already written filenames and append a counter in case of duplicates.

I like the second option:

```python
from collections import Counter
import os.path
import zipfile

# Could also be a defaultdict(int)
used_filenames = Counter()

with zipfile.ZipFile(archive_fn, "w") as zf:
    for obj in objects:
        fn = obj["orig_file_name"]
        count = used_filenames[fn]

        # If the filename was already used previously, append a number.
        # E.g. foo/bar.jpeg -> foo/bar.0.jpeg
        if count:
            name, ext = os.path.splitext(fn)
            fn = f"{name}.{count}{ext}"

        # Update counter
        used_filenames[fn] += 1

        zf.write(obj["file_name"], fn)
```

I would make a pull request but I don't know where to look for the relevant code.

Is the "backup" the original data?

**Comment by grololo06** [comment]
Hi, the code is being ported to back-end see #600 so I will solve present issue once it's done. Yes I will add something to distinguish the images, options are a counter, or even a separate sub_directory e.g. images/<sample_name>/extra_images

**Comment by moi90** [comment]
What is the time horizon for this?

**Comment by grololo06** [comment]
Mid-June (as of today!)

**Comment by grololo06** [comment]
Fixed in 2.5.9.

**Comment by moi90** [comment]
Is 2.5.9 live already? (Is there a way to find out which exact version is running on https://ecotaxa.obs-vlfr.fr ?)

**Comment by grololo06** [comment]
Hello, I generally close the issues only when the fix is live. The version number is only visible in the login page, so you have to logout first to see it...

**Comment by moi90** [comment]
Ah, great!
