### ISSUE TITLE
Explicit message during maintenance (server unavailable)

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_dev#69]
Rendre la landing page accessible mais prévoir un message lorsque la database n'est pas accessible.

**Comment by jiho** [comment]
The 404 error page should send people to ecotaxa.org where there should be some messages about the ongoing maintenance.

**Comment by grololo06** [comment]
Utiliser la page nginx pendant les maintenances.

root@newecotaxa:/home/ecotaxa# ls -als
total 561688
     4 drwxr-xr-x  9 root     root          4096 mars   7 06:13 .
     4 drwxr-xr-x 15 root     root          4096 mars   6 05:48 ..
     0 lrwxrwxrwx  1 root     root            30 janv.  9 06:47 50x.html -> /usr/share/nginx/html/50x.html

Avoir une page dédiée lorsque la **machine** n'est pas accessible est un problème d'infrastructure.
