### ISSUE TITLE
Missing value in /projects/search response

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#694]
`highest_right` field is always "" in this call, when querying for a single project it's OK.
It's a bit costly to do it for many so to fix (if not taking too long) or not (just document).

**Comment by LaurentReese** [comment]
linked with #182

**Comment by grololo06** [comment]
To fix in doc, as the project search is slow enough.

**Comment by grololo06** [comment]
Fixed there (type in message prevents proper link): https://github.com/ecotaxa/ecotaxa_back/commit/c44a4567239393b2ddfc5a6aadcd85595c8b6d00

**Comment by grololo06** [comment]
Fixed in 2.5.12
