### ISSUE TITLE
add a "save/retrieve favorite language" feature in the Swagger API.

### ISSUE THREAD

**Issue by LaurentReese** [ecotaxa/ecotaxa_dev#706]
As the mechanism is now in place on the frontend side (see files like src/locales/*.json + src/i18.ts + Home.vue::langs), we now need a way to save or retrieve a user's favorite langage.
Please comment/implement

**Comment by LaurentReese** [comment]
Basically, no need to change the API.
1) Use https://phrase.com/blog/posts/detecting-a-users-locale/ to detect the local langage
2) Use *localStorage* to store/retrieve the current selected langage, like :
```
let prenom:string|null = localStorage.getItem('prenom');
alert("prenom=" + prenom);
localStorage.setItem('prenom', 'Laurent');
```

**Comment by grololo06** [comment]
Above solution does not cover the case when a user logs in from another navigator, but is good enough for 99% of usages.

**Comment by grololo06** [comment]
In case, there is https://ecotaxa.obs-vlfr.fr/api/docs#/users/get_current_user_prefs_users_my_preferences__project_id__get
I propose to use the key "lang", which is unused so far.
