### ISSUE TITLE
Change (many) objects to WoRMS-compatible taxonomy

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#709]
It's (now) clear to me that #454 is not doable with the (sometimes implicit) constraints that we have. E.g. the system must not re-assign objects without users consent, and the current taxonomy tree is too messy to be able to express rules which treat all cases. Just to name some mess: duplicated sub-trees with variations, custom suffices, project-local naming rules and so on.

However, for various needs, e.g. export to some institutions and the sake of standardization, as much as possible of the present objects should move to "some clean system which refers to WoRMS smoothly". Bonus point if we also prevent, for the future, the bad events which occurred with the present system.

IMHO, the very first step is to define the target. 
I would go for another root in the taxonomy tree. So far we have 'living', 'not-living', 'temporary' and the new root would be named 'biota' like WoRMS one. 
This subtree would be initialized with a fresh copy of the reference DB, and would receive the following constraints, by code:
- No Phylo taxon can be added by a user. All comes from the reference DB.
- As an exception to above, first-level only Phylo children with an extension to parent can be added. _Copepoda -> Copepoda X_ is OK, but not _Copepoda -> Copepoda X -> Copepoda X sp._
- Morpho taxa can be added to any Phylo taxon with any level, e.g. _Copepoda -> Juvenile -> Female_

This is just a preliminary spec, so maybe the above is too strict, any set of (programmatically valid) rules would be OK.

Once the target is defined, it will be possible to implement a tool inspired from (or included in #509) to assist users in the transition or do it automatically in 100% sure cases.

**Comment by picheral** [comment]
Après discussion avec Laetitia : 
No Phylo taxon can be added by a user. All comes from the reference DB. **OK**
   As an exception to above, first-level only Phylo children with an extension to parent can be added. Copepoda -> Copepoda X is OK, but not Copepoda -> Copepoda X -> Copepoda X sp. **NOK**
Morpho taxa can be added to any Phylo taxon with any level, e.g. Copepoda -> Juvenile -> Female **OK**
Ces deux règles suffisent.
Un problème émerge de la première règle. Que fait-on des insectes collectés dans les filets Manta à la surface de l'océan ? Ils ne sont pas dans WORMS !
Laetitia est OK sur le fait de ne pas migrer "sous le pied des utilisateurs". Proposer un outil efficace pour le faire sur les projet de façon assistée est une bonne solution.

**Comment by grololo06** [comment]
Merci pour le feedback.
L'idée n'est pas de se débarrasser de "living" et ta remarque sur les insectes terrestres prouve que ce n'est pas possible, puisque WoRMS contient principalement du "marine". Le but est de _minimiser_ le contenu de "living" en transférant le maximum d'objets dans "biota" (et en perdant le minimum de sens).
Je viens d'entrer #710 sur le sujet.
A suivre (oralement) pour les "bonnes règles" de gestion taxo.

**Comment by grololo06** [comment]
Après discussion:
- Les suffixes par exemple sp. et X devraient être de type "Morpho", et donc suivre la dernière 'règle'
- La différence entre 'Phylo' et 'Morpho' devrait être mieux expliquée

**Comment by grololo06** [comment]
Derniers raffinements: 
- Il sera possible d'exclure certains projets de l'affichage "Deprecated", par exemple pour faire une démonstration. Dans ce cas, le menu "Fix category issues" ne sera pas montré.
- Il sera possible de récupérer les "category fixes" d'un autre projet sous contrainte des droits d'accès.

**Comment by jiho** [comment]
> L'idée n'est pas de se débarrasser de "living" et ta remarque sur les insectes terrestres prouve que ce n'est pas possible, puisque WoRMS contient principalement du "marine". Le but est de _minimiser_ le contenu de "living" en transférant le maximum d'objets dans "biota" (et en perdant le minimum de sens).

Cette remarque me fait penser que la solution à deux racines n'est pas une bonne solution. Il y a *une* racine du vivant, pas deux, et en avoir deux signifie qu'on ne saura pas où sont les choses. Il faut absolument *remplacer* la hiérarchie UniEuk par la hiérarchie WoRMS sauf dans les cas où c'est impossible. Il y aura de toute façon des additions sur la hiérarchie WoRMS (tous les morpho) donc ajouter des phylo dans le mix (ceux qui manquent dans WoRMS) n'est pas un pb majeur.

À rediscuter.

**Comment by grololo06** [comment]
#710 remains (data, not code), and of present, #733 only remains
