### ISSUE TITLE
Subset fails in a specific case

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#716]
Project 4591, filter all samples starting with "Yo", extract a subset of 100% per category, with images.

On prod', the http 500 error appears.

On my dev PC, the job hangs as well but it might be because I don't have images.

**Comment by grololo06** [comment]
The problem occurs right away, immediately after clicking 'Start Task' button.

**Comment by grololo06** [comment]
nginx log:
2021/09/15 16:15:40 [error] 1809#1809: *26443 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 193.49.112.116, server: ecotaxa.obs-vlfr.fr, request: "POST /Job/Create/Subset?p=4591&ipp=100&zoom=100&magenabled=0&popupenabled=0&samples=211625%2C211635%2C211674%2C211656%2C211600%2C211657%2C211595%2C211653%2C211638%2C211559%2C211620%2C211551%2C211561%2C211589%2C211587%2C211599%2C220553%2C220480%2C211633%2C211598%2C220494%2C220450%2C211658%2C211673%2C220466%2C220479%2C211565%2C211668%2C232397%2C232366%2C211677%2C211555%2C211659%2C211596%2C211623%2C211662%2C211588%2C211660%2C211543%2C211506%2C211621%2C211550%2C211572%2C211578%2C211569%2C211568%2C211575%2C211503%2C211644%2C211504%2C211672%2C211619%2C232340%2C232309%2C211648%2C211548%2C211577%2C211527%2C211652%2C211684%2C211615%2C211614%2C211521%2C211530%2C211666%2C211563%2C211570%2C211514%2C211512%2C211517%2C211515%2C211647%2C211533%2C211516%2C211528%2C211681%2C220546%2C220452%2C232313%2C232361%2C211523%2C211531%2C220530%2C220564%2C211583%2C211539%2C220499%2C220521%2C211678%2C211645%2C220512%2C220548%2C211518%2C211510%2C220504%2C220498%2C211540%2C211532%2C220571%2C220516%2C211669%2C211622%2C211519%2C211534%2C220444%2C220569%2C211537%2C211646%2C220509%2C220519%2C211609%2C211582%2C220551%2C220567%2C211573%2C211513%2C211520%2C211680%2C232303%2C232342%2C211664%2C211511%2C211522%2C211536%2C211538%2C211525%2C211535%2C211524%2C220531%2C220544%2C211586%2C211594%2C220554%2C220535%2C220561%2C220533%2C220563%2C220493%2C220465%2C220473%2C220514%2C220484%2C232385%2C232325%2C232417%2C232436%2C220468%2C220508%2C220449%2C220447%2C220453%2C220518%2C220458%2C220486%2C220476%2C220459%2C211642%2C211632%2C220489%2C220440%2C220500%2C220490%2C220443%2C220475%2C220482%2C220470%2C232347%2C232321%2C220462%2C220505%2C220463%2C220455%2C220441%2C220461%2C220456%2C220454%2C220467%2C220487%2C211590%2C211639%2C232356%2C232301%2C211629%2C211675%2C232442%2C232419%2C211558%2C211593%2C232388%2C232320%2C211654%2C211560%2C232311%2C232322%2C232374%2C232318%2

**Comment by grololo06** [comment]
uwsgi log:
[pid: 12453|app: 0|req: 283/21138] 193.49.112.116 () {56 vars in 7733 bytes} [Wed Sep 15 16:12:04 2021] GET /Job/Create/Subset?p=4591&ipp=100&zoom=100&magenabled=0&popupenabled=0&samples=211625%2C211635%2C211674%2C211656%2C211600%2C211657%2C211595%2C211653%2C211638%2C211559%2C211620%2C211551%2C211561%2C211589%2C211587%2C211599%2C220553%2C220480%2C211633%2C211598%2C220494%2C220450%2C211658%2C211673%2C220466%2C220479%2C211565%2C211668%2C232397%2C232366%2C211677%2C211555%2C211659%2C211596%2C211623%2C211662%2C211588%2C211660%2C211543%2C211506%2C211621%2C211550%2C211572%2C211578%2C211569%2C211568%2C211575%2C211503%2C211644%2C211504%2C211672%2C211619%2C232340%2C232309%2C211648%2C211548%2C211577%2C211527%2C211652%2C211684%2C211615%2C211614%2C211521%2C211530%2C211666%2C211563%2C211570%2C211514%2C211512%2C211517%2C211515%2C211647%2C211533%2C211516%2C211528%2C211681%2C220546%2C220452%2C232313%2C232361%2C211523%2C211531%2C220530%2C220564%2C211583%2C211539%2C220499%2C220521%2C211678%2C211645%2C220512%2C220548%2C211518%2C211510%2C220504%2C220498%2C211540%2C211532%2C220571%2C220516%2C211669%2C211622%2C211519%2C211534%2C220444%2C220569%2C211537%2C211646%2C220509%2C220519%2C211609%2C211582%2C220551%2C220567%2C211573%2C211513%2C211520%2C211680%2C232303%2C232342%2C211664%2C211511%2C211522%2C211536%2C211538%2C211525%2C211535%2C211524%2C220531%2C220544%2C211586%2C211594%2C220554%2C220535%2C220561%2C220533%2C220563%2C220493%2C220465%2C220473%2C220514%2C220484%2C232385%2C232325%2C232417%2C232436%2C220468%2C220508%2C220449%2C220447%2C220453%2C220518%2C220458%2C220486%2C220476%2C220459%2C211642%2C211632%2C220489%2C220440%2C220500%2C220490%2C220443%2C220475%2C220482%2C220470%2C232347%2C232321%2C220462%2C220505%2C220463%2C220455%2C220441%2C220461%2C220456%2C220454%2C220467%2C220487%2C211590%2C211639%2C232356%2C232301%2C211629%2C211675%2C232442%2C232419%2C211558%2C211593%2C232388%2C232320%2C211654%2C211560%2C232311%2C232322%2C232374%2C232318%2C211556%2C211592%2C232329%2C232382%2C211667%2C211655%2C232434%2C232312%2C211605%2C211604%2C232399%2C232314%2C211602%2C211597%2C232380%2C232299%2C211637%2C211636%2C232375%2C232348%2C232323%2C232330%2C211608%2C211624%2C232406%2C232401%2C211601%2C211606%2C232461%2C232306%2C211630%2C211631%2C232373%2C232317%2C211634%2C211603%2C232367%2C232307%2C211574%2C211541%2C232326%2C232351%2C232425%2C232409%2C211679%2C211665%2C232391%2C232346%2C211546%2C211505%2C232400%2C232415%2C211682%2C211650%2C220474%2C220537%2C211612%2C211547%2C220532%2C220469%2C211549%2C211610%2C220570%2C220506%2C232343%2C232354%2C211649%2C211618%2C220542%2C220524%2C211585%2C211529%2C220557%2C220555%2C211581%2C211611%2C220525%2C220517%2C211509%2C211579%2C220550%2C220495%2C211526%2C211566%2C220464%2C220526%2C211640%2C211628%2C211580%2C211651%2C220541%2C220547%2C211584%2C211567%2C220534%2C220515%2C211613%2C211617%2C220522%2C220566%2C211671%2C211544%2C220558%2C220545%2C211676%2C211616%2C220507%2C220549%2C232310%2C232338%2C211571%2C211542%2C220448%2C220527%2C211576%2C211508%2C220457%2C220510%2C211545%2C211507%2C220477%2C220497%2C211627%2C211554%2C220491%2C220488%2C211670%2C211626%2C220451%2C220560%2C211562%2C211557%2C211661%2C211663%2C220446%2C220543%2C211564%2C211643%2C220492%2C220559%2C211683%2C211641%2C220529%2C220501%2C211552%2C211591%2C220523%2C220528%2C211607%2C211553%2C220552%2C220481%2C232435%2C232327&sortorder=asc&projid=4591&pageoffset=0 => generated 13466 bytes in 169 msecs (HTTP/1.1 200) 4 headers in 430 bytes (1 switches on core 1)
2021-09-15 16:12:41 - invalid request block size: 11252 (max 8192)...skip
2021-09-15 16:13:06 - invalid request block size: 11256 (max 8192)...skip

**Comment by grololo06** [comment]
Similar to #656 but the fix done on configuration was not enough...
The request should not be a GET but a POST for filters.

**Comment by grololo06** [comment]
After checking, the code does a POST indeed, with the filters as URL.

**Comment by grololo06** [comment]
UWSGI doc, with interesting parts in bold:

buffer-size

argument: required_argument

shortcut: -b

parser: uwsgi_opt_set_64bit

help: set internal buffer size

Set the max size of a request **(request-body excluded),** this generally maps to the size of request headers. By default it is 4k. If you receive a bigger request (for example with big cookies or query string) you may need to increase it. It is a security measure too, so **adapt to your app needs** instead of maxing it out.

**Comment by grololo06** [comment]
Solution is to map filters into the form.

**Comment by grololo06** [comment]
Properly fixed in 2.5.12

**Comment by bea777515** [comment]
It is possible to check the length of the querystring in the interface before sending it to the front and choose from GET , POST
and for the 'share url' functionnality  send an error message if the querystring is too long.
extending the size of the querystring limit is a security parameter.
