### ISSUE TITLE
Selected vignette is displayed wrongly if it is unclassified

### ISSUE THREAD

**Issue by LaurentReese** [ecotaxa/ecotaxa_dev#723]
For an unclassified object, the selection makes the entire background color becoming pink.
For a predicted or dubious object, the object is selected with pink background while the rest of the objet stays blue or green.

**Comment by LaurentReese** [comment]
![image](https://user-images.githubusercontent.com/74904892/134379652-e9a27def-d9b6-4a19-a4b9-81fdce1f5e2e.png)
==> Good

**Comment by grololo06** [comment]
Side-by-side 
![image](https://user-images.githubusercontent.com/20199778/134467446-e7202284-93ff-41f2-acb6-e5fe4b1cbcc2.png)

**Comment by grololo06** [comment]
Verified just now.
