### ISSUE TITLE
Améliorer la sélection multiple

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#93]
Pour Project, Instrument, Sample, au moins.

Il faudrait rendre plus facile la sélection de plusieurs éléments à la fois. Actuellement c'est possible mais il faut les sélectionner un par un dans la liste (ou les cliquer dans la liste pour Sample > Advanced).

Il faudrait:
- quand le champ est sélectionné, ouvrir la liste d'autocomplétion (comme actuellement)
- permettre les wildcard dans l'autocomplétion (idéalement * plutôt que %, qui est plus facilement compris). Voire, faire du wilcard par défaut ("point B" sélectionne tout ce qui contient la chaine de caractère, pas juste ce qui commence par cette chaine).
- dans la liste qui s'ouvre, permettre de la sélection multiple, avec SHIFT et CTRL/COMMAND (cela revient à garder la liste ouverte et enlever les éléments déjà sélectionnés)

Cela ne semble pas possible avec select2 mais l'est avec selectize: https://selectize.github.io/selectize.js/ (ou chosen: https://harvesthq.github.io/chosen/)

Cas d'utilisation: en explore, je veux sélectionner tous les projets point B régent. Actuellement il faut que je filtre la liste n fois.

**Comment by picheral** [comment]
cf #183

**Comment by picheral** [comment]
JO, veux-tu vérifier que ce qui a été fait et validé en #183 est suffisant pour clore cette issue ?

**Comment by picheral** [comment]
Passé en 2.x.... sauf si rapide à implémenter !

**Comment by jiho** [comment]
Pistes:

- clicks multiples : `closeOnSelect: false`
- supprimer les éléments choisis de la liste des possibilités: https://stackoverflow.com/questions/36682901/how-to-remove-selected-option-from-the-option-list-in-select2-multiselect-and-sh

**Comment by picheral** [comment]
Vu le coup de programmer cet nvx UX et de le tester ensuite, nous décidons de reporter en 2.x. et après discussion sans urgence. 
Cela permet de déployer 1.6 sauf si indispensable sur certains champs particuliers.

**Comment by picheral** [comment]
En le gardant ouvert, c'est en effet plus pratique et plus intuitif que CTRL (même sous Windows) pour la sélection multiple et ça me semble relativement intuitif pour la sélection simple (il suffit de cliquer au dehors).

Il manque le fait de supprimer les éléments déjà sélectionnés.

Il faut que cela fonctionne de façon *exactement* identique pour toutes les select box utilisant select2, partout (de même que le système de wildcard). En effet cela demande des efforts maintenant, mais ça diminue l'effort de tous les utilisateurs et de nous même quand nous expliquons comment EcoTaxa fonctionne.


La question à laquelle je n'ai pas de réponse c'est s'il est plus simple de modifier le composant que nous avons déjà (select2) ou d'en choisir un autre. Les choix sont grosso modo ceux notés dans l'issue https://github.com/oceanomics/ecotaxa_dev/issues/93
cf https://alternativeto.net/software/select2/ = les trois principaux sont select2, selectize, et chosen
Or les trois semblent un peu morts (https://github.com/select2/select2/issues/4953). L'alternative semble être des frameworks javascripts plus complets (genre Vue.js) et, s'il faudra peut-être s'y mettre à un moment, ce n'est pas maintenant.

Parmi les trois, selectize.js me semble le plus élégant et fonctionne (en multiselect) presque exactement comme je pense qu'il le faudrait.
Testez "Email contacts" sur https://selectize.github.io/selectize.js/: taper des caractères limite les possibilités en cherchant n'importe ou dans le texte des possibilités (espace = wildcard mais ça cherche même sans ordre, i.e. "a i" = "i a" = "a*i" etc.), cliquer ouvre le champ, sélectionner un élément le supprime de la liste des possibilités. Ce qui manque c'est que si je tape "te" ça limite la liste des possibles aux éléments contenant "te" mais en choisir un supprime ce filtre et les ré-affiche tous; il faudrait pouvoir conserver le filtre.

Mais, quelque soit le choix, il sera probablement amené à changer étant donné le statut de développement de ces projets. DONC (enfin) je pense que Laurent, vous être le mieux placé pour savoir ce qui sera le plus efficace, maintenant. Les spécifications voulues sont là:
https://github.com/oceanomics/ecotaxa_dev/issues/93#issuecomment-437899601
les 1 et 2 me semblent faisables pour la 1.6, la 3 pourra attendre plus tard.

**Comment by grololo06** [comment]
Issue trop large avec trop d'historique.
